### ISSUE TITLE
[BUG] Output dimensions are no longer dynamic after simplifying

### ISSUE THREAD

**Issue by FamousDirector** [daquexian/onnx-simplifier#101]
**Describe the bug**
I simplified the model and the output layer no longer dynamic (I would expect it to be -1, 512). I used the following command: `python3 -m onnxsim osnet_ain_fused.onnx osnet_ain_fused_simplified.onnx --input-shape input:8,256,128,3`

**Model**
Here is a [link](https://drive.google.com/file/d/1dcZ8Yo11jgPRRxv9_nImX_Xu3MJr0C6E/view?usp=sharing) to the model. 

Please let me know if you have any other questions.

**Comment by daquexian** [comment]
Sorry for the late reply. It is how onnxsim works. onnxsim, for now, cannot handle dynamic input shapes, so dynamic input shapes must be fixed as static.

**Comment by daquexian** [comment]
In v0.2.24 dynamic input shape is supported. Please pass `--dynamic-input-shape` if you don't want the input shape to be overwritten.
