### ISSUE TITLE
libprotobuf ERROR google/protobuf/descriptor_database.cc:57

### ISSUE THREAD

**Issue by StrongerzZ** [daquexian/onnx-simplifier#103]
Hi, 
When I run **from onnxsim import simplify**,
I got the following error:

[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: onnx/onnx-ml.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1164] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 

Can someone help me solve it? Thanks!

**Comment by daquexian** [comment]
It is likely due to the new `onnxoptimizer` (which is also maintained by me). Could you please provide your OS and python version? Thanks!

**Comment by daquexian** [comment]
BTW, do you have onnx built from the source?

**Comment by StrongerzZ** [comment]
I use nvidia jetson xavier nx, ubuntu 18.04, python3.6.
I installed onnx using pip, and did not built from the source.
onnx-simplifier built from the source.
@daquexian

**Comment by daquexian** [comment]
请问你安装 onnx-simplifier 的具体操作是怎样的呢，特别是涉及到 onnxoptimizer 的部分

**Comment by StrongerzZ** [comment]
是这样的：

pip install -i https://pypi.tuna.tsinghua.edu.cn/simple onnx
git clone --recursive https://github.com/onnx/optimizer onnxoptimizer
cd onnxoptimizer
pip3 install -e .
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple onnx-simplifier

刚才说的好像有点问题，onnxoptimizer是源码安装的，onnx-simplifier是pip安装的。
@daquexian

**Comment by daquexian** [comment]
了解了。和我猜测的差不多，是因为 nvidia jetson xavier nx 是 arm 架构的，onnx 没有提供 arm 架构的预编译包，所以你用 pip install 安装的时候，实际上 pip 也是帮你下载源码编译安装的，再加上 onnxoptimizer 也是编译安装的，编译安装默认会使用动态链接的 protobuf，就会出问题。建议先换到 x86 机器上使用 onnx-simplifier

**Comment by StrongerzZ** [comment]
有什么方法能解决吗。。
因为要在NX上跑trt，x86架构生成的.engine文件不兼容NX。
我的另一个NX上是可以跑onnx-simplifier的,但是我忘了具体是怎么安装的了。。
之前的pycharm环境里可以看见：
onnx 1.7.0
onnx-simplifier 0.2.16
onnxruntime 1.4.0
现在pycharm环境里多了一个onnxoptimizer，而且卸载不掉：
onnx 1.8.0
onnx-simplifier 0.2.19
onnxruntime 1.5.2
onnxoptimizer 0.1.1
@daquexian

**Comment by daquexian** [comment]
其实可以在 x86 上运行 onnx-simplifier，把生成的新 onnx 模型放在 nx 上转 trt 的。也可以退回到 0.2.18 版本，pip install onnx-simplifier==0.2.18

**Comment by StrongerzZ** [comment]
是的，刚想回复你来着，问题已经解决了，但还是希望能出一个arm架构的版本。
总之，再次感谢！ @daquexian

**Comment by daquexian** [comment]
> 是的，刚想回复你来着，问题已经解决了，但还是希望能出一个arm架构的版本。

好，我会研究一下的！

**Comment by daquexian** [comment]
> 是的，刚想回复你来着，问题已经解决了，但还是希望能出一个arm架构的版本。

我快速的看了一下，manylinux（跨 linux 发行版的 python 包标准）不支持 arm，这意味着没法做出一个对 arm linux 通用的 python 包，也不能把它上传到 pypi。看来需要想别的办法解决这个问题。

**Comment by yinjiayang** [comment]
这个问题怎么解决的，我现在也遇到这个问题了，在nvidia jeston AGX上
