### ISSUE TITLE
[BUG] torch1.5 export的模型不能合并bn

### ISSUE THREAD

**Issue by luoqing94** [daquexian/onnx-simplifier#104]
**Describe the bug**
torch1.5导出的模型使用工具不能合并bn，请问是正常的吗？

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

**Comment by daquexian** [comment]
你好，是正常的。在 onnx 自带的 optimizer 模块里，fuse conv bn 的 optimizer 有一些问题，所以 onnx-simplifier 默认禁用了。如果想开启可以手动传入 --enable-fuse-conv-bn 参数。

现在 onnx optimizer 模块独立成了一个专门的 repo，我是 maintainer 之一，相关的 bug 已经修复，很快就可以用新的 onnx optimizer 并默认开启 fuse conv bn 了，敬请期待

**Comment by daquexian** [comment]
issue 先关掉啦，还有问题的话请随时 reopen

**Comment by luoqing94** [comment]
> 你好，是正常的。在 onnx 自带的 optimizer 模块里，fuse conv bn 的 optimizer 有一些问题，所以 onnx-simplifier 默认禁用了。如果想开启可以手动传入 --enable-fuse-conv-bn 参数。
> 
> 现在 onnx optimizer 模块独立成了一个专门的 repo，我是 maintainer 之一，相关的 bug 已经修复，很快就可以用新的 onnx optimizer 并默认开启 fuse conv bn 了，敬请期待

感谢回复，期待新的repo

**Comment by daquexian** [comment]
最新版 onnx simplifier 已经默认开启 fuse conv bn :)
