### ISSUE TITLE
TypeError: Error while converting op of type: Reshape. Error message: Reshape dimention number shall be 2 or 4

### ISSUE THREAD

**Issue by ruabliuqiu** [daquexian/onnx-simplifier#105]
**Describe the bug**
When convert onnx to caffe model ,I have encountered such a mistake. the onnx model had converted by onnx-simplifier.

**Model**

Reshape、Transpose nodes still exist, How do I remove these nodes

**Comment by xinxin12345** [comment]
> **Describe the bug**
> When convert onnx to caffe model ,I have encountered such a mistake. the onnx model had converted by onnx-simplifier.
> 
> **Model**
> 
> Reshape、Transpose nodes still exist, How do I remove these nodes

Have you solved it？ I also encountered this problem.

**Comment by daquexian** [comment]
I think this issue is not related to onnx-simplifier. Please submit an issue to the onnx-to-caffe converter you used. Thanks! :)
