### ISSUE TITLE
遇到了未知错误：“RuntimeError: unreachable”，可以尝试向 onnx 开发者反馈

### ISSUE THREAD

**Issue by wwdok** [daquexian/onnx-simplifier#106]
I tried to optimize [this onnx model](https://drive.google.com/file/d/1en7Ro5zfiVsGHLJdpUE6c1OkeINV_Wr2/view?usp=sharing), but encounter below error : 

![image](https://user-images.githubusercontent.com/43233772/101109562-23087480-3612-11eb-94ce-67282b62e5a5.png)

**Comment by daquexian** [comment]
你好，web 版目前是 alpha 阶段，可能有 bug，遇到问题可以使用 python 版
