### ISSUE TITLE
[BUG] onnx模型转为onnx-sim模型过程中提示输出为nan

### ISSUE THREAD

**Issue by xidiancpy** [daquexian/onnx-simplifier#110]
**Describe the bug**
onnx模型使用onnxruntime可以正常执行且输出结果，但是转换onnx-sim模型是提示如下图所示
![image](https://user-images.githubusercontent.com/26536004/103075590-d4de0400-4606-11eb-8a5b-66758fd41d35.png)
Simplifying...
Checking 0/3...
Tensor 1082 changes after simplifying. The max diff is nan.
Note that the checking is not always correct.
After simplifying:
[[[[nan nan nan ... nan nan nan]
   [nan nan nan ... nan nan nan]
   [nan nan nan ... nan nan nan]
   ...
   [nan nan nan ... nan nan nan]
   [nan nan nan ... nan nan nan]
   [nan nan nan ... nan nan nan]]]]
Before simplifying:
[[[[nan nan nan ... nan nan nan]
   [nan nan nan ... nan nan nan]
   [nan nan nan ... nan nan nan]
   ...
   [nan nan nan ... nan nan nan]
   [nan nan nan ... nan nan nan]
   [nan nan nan ... nan nan nan]]]]
----------------
Check failed, please be careful to use the simplified model, or try specifying "--skip-fuse-bn" or "--skip-optimization" (run "python3 -m onnxsim -h" for details)

**Model**
模型已经发送至邮箱daquexian566@gmail.com

**Comment by xidiancpy** [comment]
望回复

**Comment by jinfagang** [comment]
@xidiancpy  @daquexian Same issue here. Some models may have specific operation which hightly depends on input data. It may generate Nan result if input is random, for instance, SOLOv2 model, I found the matrix nms part might output Nan if input is random. I don't know what's the reason but it's necessary feeds a reasonable data to onnx-sim for model checking. Not sure if there exist such interface or not inside onnx-simpilifier for now. If does anyone could shine some lights on me?

**Comment by daquexian** [comment]
@jinfagang I also noticed this problem. There is a pr fixing it https://github.com/daquexian/onnx-simplifier/pull/61 but not merged yet (this is my fault 😂). I have a question: how do you run pre-processing if you want to feed a real input data?

**Comment by jinfagang** [comment]
@daquexian directly using same data feeds into model, I mean, the one after preprocessing. It can be feeded easily using API possibly. Also, will it effect the final optimization of graph if we skip checking with data input in such situation?

**Comment by daquexian** [comment]
> will it effect the final optimization of graph if we skip checking with data input in such situation

No, you can feel free to skip it if you don't want to check the equality
