### ISSUE TITLE
新版yolov5转ncnn出现段错误，我切换旧版就好了[BUG] 

### ISSUE THREAD

**Issue by lengxia** [daquexian/onnx-simplifier#111]
**Describe the bug**

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

**Comment by daquexian** [comment]
你好，旧版是指旧版 onnx-simplifier 还是旧版 yolov5 呢

**Comment by lengxia** [comment]
> 你好，旧版是指旧版 onnx-simplifier 还是旧版 yolov5 呢

旧版onnx-simplifier ，19版本， 并且最新的ncnn 优化器也有问题，ncnn也得用上一个版本，总之，除了yolov5，全得用上一个版本，折腾我一天多了

**Comment by daquexian** [comment]
也就是说最新版 onnx-simplifier + 旧版 ncnn 也是不行的吗

**Comment by lengxia** [comment]
> 也就是说最新版 onnx-simplifier + 旧版 ncnn 也是不行的吗

这个我没试过哎，原始的onnx 是可以的，但是sim后出现段错误，然后我切换了旧版sim，就好了，然后再做ncnnoptim优化的时候ncnn又出现段错误，我切换旧版ncnn就好了，我担心这个问题会有很多人遇到

**Comment by daquexian** [comment]
> 原始的onnx 是可以的，但是sim后出现段错误

是指哪个阶段出现段错误呢

**Comment by lengxia** [comment]
onnx2ncnn

**Comment by nihui** [comment]
导出onnx时，可以用 opset version 11
因为onnx opset12改了些东西不兼容了，不过最新的 onnx2ncnn 代码已经修复段错误啦

**Comment by daquexian** [comment]
> 导出onnx时，可以用 opset version 11
因为onnx opset12改了些东西不兼容了，不过最新的 onnx2ncnn 代码已经修复段错误啦

好！那我就把这个 issue 关掉啦
