### ISSUE TITLE
[BUG] Shape not supported yet! Gather not supported yet! # axis=0 Unsupported unsqueeze axes ! Unknown data type 0

### ISSUE THREAD

**Issue by wwdok** [daquexian/onnx-simplifier#126]
**Describe the bug**
I retrained a resnet18 model with pytorch 1.7, after finishing training, i tried to use [web tool](https://convertmodel.com/) to convert this model to ncnn format, but it reported error:

```
Shape not supported yet!
Gather not supported yet!
# axis=0
Unsupported unsqueeze axes !
Unknown data type 0
```

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com
https://drive.google.com/file/d/12rZSCyUNIuU9HkBEeZ14KPmE2ieVnZlS/view?usp=sharing

**Comment by daquexian** [comment]
Thanks for your issue! Which version of onnxsim do you use, web version or
python version? Web version is in its very alpha stage. Please use python
version instead

**Comment by wwdok** [comment]
Hi, previously i use web version, then it failed, now i follow your suggestion that using python version, so i use `python -m onnxsim resnet18_special_vehicle.onnx resnet18-sim.onnx` to get the simpified onnx model, next i check its op with netron, find there is already no shape and gather op, so i use web version to convert onnx format to ncnn format, this time it succesus ! But i find the simplified onnx model and ncnn model are both 40+ MB like orginal onnx model, it seems not simplify model actually, is this normal ? Thanks !

**Comment by daquexian** [comment]
Congratulations!

It is normal. simplification here is removing the nodes which can be
removed, like most shape nodes. For some models, the size will decrease a
lot. But not all models are so.

weida wang <notifications@github.com> 于 2021年2月23日周二 下午6:21写道：

**Comment by wwdok** [comment]
Got it, thanks for your confirmation !
