### ISSUE TITLE
Can't recognize custom op

### ISSUE THREAD

**Issue by yellowYuga** [daquexian/onnx-simplifier#128]
I want to  modify onnx model with a grid_sample op and simplify it.
The onnx model looks like this:
![image](https://user-images.githubusercontent.com/32639257/109110163-8b7a7400-7771-11eb-879f-ea0552119af8.png)

The code to simplify onnx model like this:
model_simp, check = simplify(model,custom_lib='./custom_op_library.dll')

But it raised error:
```
Warning: Unsupported operator grid_sample. No schema registered for this operator.
Warning: Unsupported operator grid_sample. No schema registered for this operator.

Process finished with exit code -1073741819 (0xC0000005)
```
I have registered it in ORT (file in \onnxruntime\core\graph\contrib_ops ) like this:
```
 ONNX_CONTRIB_OPERATOR_SCHEMA(GridSample)
.SetDomain(kMSDomain)
.SinceVersion(1)
      .SetDoc(
          "Pytorch Grid Sample by Huang Yujia ")
      .Input(0, "input", "Input tensor.", "T")
      .Input(1, "grid", "Input tensor.", "T")
      .Output(0, "Y", "Output tensor of the same type and shape as the input tensor.", "T")
      .TypeConstraint(
      "T",
      {"tensor(float16)",
       "tensor(float)",
       "tensor(double)"},
      "Constrain input and output types to float tensors.")
      .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
        for (size_t i = 0; i < ctx.getNumInputs(); ++i) {
          propagateElemTypeFromInputToOutput(ctx, i, i);
          if (hasInputShape(ctx, i)) {
            propagateShapeFromInputToOutput(ctx, i, i);
          }
        }
      });
```

I don't know what went wrong.Is there something wrong with my .dll?

**Comment by yellowYuga** [comment]
I tried `custom_lib='./custom_op_library.dll'` with no custom op (Only the source code of onnxruntime).
With onnx like this(test example in \onnxruntime\test\testdata\custom_op_library/ custom_op_test.onnx):
![image](https://user-images.githubusercontent.com/32639257/109131375-b8d51b00-778d-11eb-871c-5823220cacf3.png)
It rasied error:
`Process finished with exit code -1073741819 (0xC0000005)`

When onnx model like this(inverse op is implemented in ORT):
![image](https://user-images.githubusercontent.com/32639257/109132281-9e4f7180-778e-11eb-9098-44f1bbf7f04e.png)
It raised error:
```
Warning: Unsupported operator Inverse. No schema registered for this operator.
Warning: Unsupported operator Inverse. No schema registered for this operator.

Process finished with exit code -1073741819 (0xC0000005)
```


Thank you for the help.

**Comment by daquexian** [comment]
@tangyanf could you please help take a look? :) I'm not familiar with ort custom libs.

**Comment by yellowYuga** [comment]
I figured out why it crashed. The latest version of ORT (master branch) has bugs, so I switched to 1.6.0 and it was all done. But thank you guys anyway.

**Comment by daquexian** [comment]
Good news!
