### ISSUE TITLE
精度是否会受影响

### ISSUE THREAD

**Issue by luuuyi** [daquexian/onnx-simplifier#13]
你好，我用代码将onnx简化以后转ncnn，在分类任务中NCNN出来的logit和pytorch出来的结果精度在小数点后一位存在不一致，请问下是不是简化过程中比如合BN什么的影响了精度。

**Comment by daquexian** [comment]
你好，一般不会的，如果不放心可以看一下有一个参数可以跳过合并 bn 的步骤

**Comment by luuuyi** [comment]
@daquexian 刚用onnxruntime测试了一下，精度没问题，问题只有可能出在ncnn了，请问下你有什么指导经验么

**Comment by daquexian** [comment]
不好意思没有太多经验 QAQ

**Comment by luuuyi** [comment]
@daquexian 好的，感谢。
