### ISSUE TITLE
Gather not supported yet!   # axis=0

### ISSUE THREAD

**Issue by ciwei123** [daquexian/onnx-simplifier#130]
@daquexian Thanks for your sharing. I successfully converted the pytorch model to onnx model, and I have simplified the onnx model. After simplification, the unsqueeze operation and gather operation are reduced, but there are still a few left. When I convert the onnx model to ncnn, I get the error:
**Gather not supported yet!
 axis=0**

I tried several methods, but no success:
**method 1**: when onnx export ,add the "keep_initializers_as_inputs=true"
**method2:** install the onnx-simplifier  then  python3 -m onnxsim input_onnx_model output_onnx_model
**method 3:** I download the [https://github.com/daquexian/onnx-simplifier]，and use `the from onnxsimplifiermaster.onnxsim.onnx_simplifier import simplify`

ubuntu16.04
cuda 10.1
pytorch1.3
onnx 1.8.1
onnx-simplifier 0.2.18
onnxruntime 1.7.0

[code:](https://github.com/lidq92/MDTVSFA/blob/main/VQAmodel.py)
Thank you very much!!

**Comment by daquexian** [comment]
Thanks for your issue! 

onnxsim does not guarantee all ops incompatible with ncnn can be eliminated

**Comment by ciwei123** [comment]
@daquexian Thanks for your reply. Could you tell me what rules to eliminate?Is it possible to know that certain operations cannot be eliminated before simplification?Thank you very much!!

And I have solved the error:
**Gather not supported yet!
axis=0**
the method: q[0,:128]-->q.view(128,1)

**Comment by daquexian** [comment]
Sorry for the late reply. The indexing operation (like tensor[idx1:idx2])
will be converted to "gather" op in onnx, and cannot be eliminated in most
cases.
