### ISSUE TITLE
[BUG] [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION 

### ISSUE THREAD

**Issue by zhejiang627** [daquexian/onnx-simplifier#133]
**Describe the bug**
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'Mul_491' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:487 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 3 by 15

**Model**
https://github.com/ultralytics/yolov5/releases/download/v4.0/yolov5s.pt

**Comment by daquexian** [comment]
Hi, does this issue still exist? To my knowledge, yolov5 has [used onnxsim officially](https://github.com/ultralytics/yolov5/pull/2815), so yolov5 is definitely supported by onnxsim.

**Comment by zhejiang627** [comment]
Thank you. I suppose that i used the old version of yolov5.
