### ISSUE TITLE
[BUG]  maxpool support error.

### ISSUE THREAD

**Issue by leaf918** [daquexian/onnx-simplifier#134]
**Describe the bug**

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

`
---------------------------------------------------------------------------
Fail                                      Traceback (most recent call last)
<ipython-input-6-75e1c84a420f> in <module>
      6 
      7 # convert model
----> 8 model_simp, check = simplify(model)
      9 
     10 assert check, "Simplified ONNX model could not be validated"

/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py in simplify(model, check_n, perform_optimization, skip_fuse_bn, input_shapes, skipped_optimizers, skip_shape_inference, input_data, dynamic_input_shape, custom_lib)
    478         return model
    479 
--> 480     model = fixed_point(model, infer_shapes_and_optimize, constant_folding)
    481 
    482     # Overwrite model input shape

/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py in fixed_point(x, func_a, func_b)
    379     """
    380     x = func_a(x)
--> 381     x = func_b(x)
    382     while True:
    383         y = func_a(x)

/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py in constant_folding(model)
    468         const_nodes = get_constant_nodes(
    469             model, dynamic_input_shape=dynamic_input_shape)
--> 470         res = forward_for_node_outputs(model,
    471                                        const_nodes,
    472                                        input_shapes=updated_input_shapes,

/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py in forward_for_node_outputs(model, nodes, input_shapes, input_data, custom_lib)
    224     model = copy.deepcopy(model)
    225     add_features_to_output(model, nodes)
--> 226     res = forward(model,
    227                   input_data=input_data,
    228                   input_shapes=input_shapes,

/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py in forward(model, input_data, input_shapes, custom_lib)
    192     sess_options.graph_optimization_level = rt.GraphOptimizationLevel(0)
    193     sess_options.log_severity_level = 3
--> 194     sess = rt.InferenceSession(model.SerializeToString(
    195     ), sess_options=sess_options, providers=['CPUExecutionProvider'])
    196 

/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py in __init__(self, path_or_bytes, sess_options, providers, provider_options)
    278 
    279         try:
--> 280             self._create_inference_session(providers, provider_options)
    281         except RuntimeError:
    282             if self._enable_fallback:

/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py in _create_inference_session(self, providers, provider_options)
    307             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    308         else:
--> 309             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
    310 
    311         # initialize the C++ InferenceSession

Fail: [ONNXRuntimeError] : 1 : FAIL : Node (MaxPool_2) Op (MaxPool) [ShapeInferenceError] Attribute strides has incorrect size
`

**Comment by daquexian** [comment]
Thanks for your issue. In your model there is a MaxPool3d with 4-d input. It makes the model incorrect.
