### ISSUE TITLE
The exported model size of fp32 and fp16 are the same

### ISSUE THREAD

**Issue by wwdok** [daquexian/onnx-simplifier#137]
I noticed there is an option "产生fp16模型" in the webpage, so i want to know what is the default export precision ? is it fp32 ?  Also i find the model size didn't change : 
![image](https://user-images.githubusercontent.com/43233772/113237666-d55afa80-92d9-11eb-839b-fa0eb9c716a5.png)
Is this means the two version actually already have the same precision - fp16 ?

**Comment by daquexian** [comment]
Thanks for your issue. It may be a bug of convertmodle.com. I will check it
soon

weida wang ***@***.***> 于 2021年4月1日周四 上午11:05写道：

**Comment by wwdok** [comment]
Thank you, my import onnx model is here
[nanodet-sim.zip](https://github.com/daquexian/onnx-simplifier/files/6243834/nanodet-sim.zip)

**Comment by daquexian** [comment]
Fixed
