### ISSUE TITLE
[BUG] how to make it recogize onnx custom op?

### ISSUE THREAD

**Issue by dedoogong** [daquexian/onnx-simplifier#138]
**Describe the bug**
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for ASLFeatPluginX with domain_version of 13
 
**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

I added and rebuilt the onnx-runtime with my own custom kernel but I still failed to run onnx-simplifier.
Do I need to add custom op to onnx too? if not what/how to avoid this error??

Thank you!

**Comment by daquexian** [comment]
You may want to use https://github.com/daquexian/onnx-simplifier/blob/master/onnxsim/__main__.py#L31

**Comment by dedoogong** [comment]
thank you! but could you please guide me littlie bit more?
After I build onnx runtime, I got onnxruntime_custom_op_library.so which seems to contain all custom modules. 
Do you guess I need to use the custom-lib option like "--custom-lib ~/onnxruntime_custom_op_library.so" ?? or do I need to refer another custom onnx(not onnx-runtim) so file??
Thank you

**Comment by daquexian** [comment]
Sorry for the late reply. 

> Do you guess I need to use the custom-lib option like "--custom-lib ~/onnxruntime_custom_op_library.so"

Yes. I myself am not familiar with onnxruntime custom lib. Does the problem still exist now?
