### ISSUE TITLE
How to  simplify the Shape, Gather, Unsqueeze operators in the mobilenetv2-7.onnx model?

### ISSUE THREAD

**Issue by yangjing69** [daquexian/onnx-simplifier#140]
Hi, I'm using onnxsim to simplify the Shape, Gather, Unsqueeze operators in the mobilenetv2-7.onnx model and I'm having problems.
My python code:
![python_code](https://user-images.githubusercontent.com/46013903/114504492-88740e00-9c61-11eb-9d02-0fa49025ab4c.png)

Model before simplification:
![model_before_onnxsim](https://user-images.githubusercontent.com/46013903/114504537-96c22a00-9c61-11eb-89b6-c12c2ff1810b.png)

Model after simplification:
![model_after_onnxsim](https://user-images.githubusercontent.com/46013903/114504572-a6da0980-9c61-11eb-8d42-ac72d47a0a5e.png)

Simplified model Reshape operator's shape value is incorrect, it becomes [1,18446744073709551615] .
How should I Solve the problem？

**Comment by Ein42** [comment]
I have the same puzzle

**Comment by daquexian** [comment]
Sorry for the late reply. I'll check it today

**Comment by daquexian** [comment]
I think it is a bug of netron ui. The real value is -1 and 18446744073709551615 you saw is 2^64-1. It's likely that netron doesn't show "-1" correctly.

If the output message of onnxsim is like:

> Checking 0/3...
> Checking 1/3...
> Checking 2/3...
> Ok!

that means the simplified model is correct and you don't need to worry

**Comment by daquexian** [comment]
Closing the issue. If your problem is not solved, feel free to reopen it.
