### ISSUE TITLE
[BUG]  [ShapeInferenceError] Incompatible dimensions

### ISSUE THREAD

**Issue by stevenwudi** [daquexian/onnx-simplifier#142]
**Describe the bug**

When I tried to convert the model of YOLOV5S, there is a bug:

sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Mul_959) Op (Mul) [ShapeInferenceError] Incompatible dimensions

onnx.__version__
'1.9.0'
onnxsim.__version__
'0.3.5'
torch.__version__
'1.8.1+cu111'

**Model**

The model is from pytorch model from the official yolov5 model:
https://github.com/ultralytics/yolov5/releases

Looking forward to hear back!

**Comment by stevenwudi** [comment]
This problem is raised in the issue in yolov5 and solve in PR# 2982
https://github.com/ultralytics/yolov5/issues/2558
PR:
https://github.com/ultralytics/yolov5/pull/2982

**Comment by daquexian** [comment]
Great! :)
