### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zhenglongjiepheonix** [daquexian/onnx-simplifier#153]
请问shape inference是为了得到每个Value的shape和elem_type信息然后方便适配optimizer里面的pass吗？

**Comment by zhenglongjiepheonix** [comment]
那如果shape inference失败了会不会引起optimizer里面有关shape的pass产生一些错误啊

**Comment by zhenglongjiepheonix** [comment]
或者说onnxoptimizer里面的这些Value的信息是通过shape inference得到的吗

**Comment by daquexian** [comment]
> 请问shape inference是为了得到每个Value的shape和elem_type信息然后方便适配optimizer里面的pass吗？

是的，有些 pass 依赖 shape 信息

> 那如果shape inference失败了会不会引起optimizer里面有关shape的pass产生一些错误啊

不会的，没有 shape 信息的时候就会跳过

**Comment by daquexian** [comment]
有问题欢迎继续问
