### ISSUE TITLE
[BUG] Constant folding will clean costom op

### ISSUE THREAD

**Issue by FRAOTIAC** [daquexian/onnx-simplifier#159]
**Describe the bug**
When simplify a onnx model with custom ops, it will see it as a constant node, then removes it. 
**Model**
![image](https://user-images.githubusercontent.com/16257151/137475806-978b837b-7b3c-4312-89d7-9bbee80613f9.png)

![image](https://user-images.githubusercontent.com/16257151/137475796-54450dc5-9470-4fe0-8e41-882e59f1f50b.png)

How to fix: 
By add a feature to pass custom op names to `simplify() `, then skip the custom op in `constant_folding()`

**Comment by daquexian** [comment]
Sorry for the late response. It is fixed in the latest version.
