### ISSUE TITLE
onnx.optimizer

### ISSUE THREAD

**Issue by TaucherLoong** [daquexian/onnx-simplifier#167]
since onnx.optimizer was removed from onnx1.10.2, while import onnx.optimizer, it reported ModuleNotFoundError:No module named 'onnx optimizer'

**Comment by daquexian** [comment]
Thanks for your issue. The latest onnx-simplifier doesn't have this problem. Could you please verify it?

**Comment by TaucherLoong** [comment]
my jetson nano can only 'pip install onnx_simplifier<=0.2.18

**Comment by TaucherLoong** [comment]
could you give me instructions how to setup from source？

**Comment by daquexian** [comment]
Sorry for the late response. It has been fixed in onnxoptimizer 0.2.7.
