### ISSUE TITLE
[BUG] unsupported ops Shape\Resize\ArgMax

### ISSUE THREAD

**Issue by zhiboniu** [daquexian/onnx-simplifier#168]
**Describe the bug**

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

I still got unsupported ops after onnxsim,
the log is:
```
Shape not supported yet!
Unknown data type 0
Unsupported Resize scales and sizes are all empty!
Shape not supported yet!
Unknown data type 0
Unsupported Resize scales and sizes are all empty!
Shape not supported yet!
Unknown data type 0
Unsupported Resize scales and sizes are all empty!
ArgMax not supported yet!
  # axis=-1
  # keepdims=0
```

**Comment by zhiboniu** [comment]
@daquexian
[tinypose256.onnx.zip](https://github.com/daquexian/onnx-simplifier/files/7852153/tinypose256.onnx.zip)
 1.python3 -m onnxsim tinypose256.onnx tinypose256-sim.onnx
2.onnx2ncnn tinypose256-sim.onnx tinypose256.param tinypose256.bin

**Comment by daquexian** [comment]
Sorry for the late reply. onnxsim does not guarantee that **all** Shape op can be eliminated
