### ISSUE TITLE
 did onnxsim can elimate the shape ,gather,cast  op.etc with dynamic shape input of onnx? example:F.interpolate(x,scale_factor=2,mode='nearest') + y

### ISSUE THREAD

**Issue by cqray1990** [daquexian/onnx-simplifier#170]
**Describe the bug**

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

did onnxsim can elimate the shape ,gather,cast  op.etc with dynamic shape input of onnx?

**Comment by daquexian** [comment]
onnxsim doesn't guarantee eliminating shape, gather, cast ops. Instead, it only eliminate these ops (as well as all other ops) when op inputs are constant.

So in most cases, shape ops will not be eliminated with dynamic shape input.
