### ISSUE TITLE
not find an implementation for the node Add

### ISSUE THREAD

**Issue by qiuhaining** [daquexian/onnx-simplifier#18]
![image](https://user-images.githubusercontent.com/23293902/63904114-77ea3200-ca42-11e9-862c-d42fb0c14574.png)

**Comment by daquexian** [comment]
Could you please send the model to me by email? My email address is daquexian566@gmail.com

**Comment by daquexian** [comment]
The onnx opset version is old. At least opset 7 is needed, while your model is opset 6. Please upgrade your pytorch version and re-generate the onnx model.
