### ISSUE TITLE
Web portal and out-of-date local onnxrutime dependency issues.

### ISSUE THREAD

**Issue by mexico-johnny** [daquexian/onnx-simplifier#181]
Discovered your tool recently and attempted to use it both from the website and locally and ran into a couple of issues:

1) Via the web portal, I was attempting to simplify an test onnx model and the website prompted me to enter the 'input' shape of the model.  Using Netron, I determined the input shape, and tried many permutations, but was unable to find any combination that worked.  If you could provide sometime of an example that would guide users that would be very helpful.

2) I attempted to pip (22.04) install the packages locally on my Windows 10 box and ran into onnxruntime package dependency issues (see below).  The latest version of the onnxruntime is 1.11.0, however, it appears that tool is somewhat outdated.  Any plans to upgrade it to work with the latest?

Interesting tool. Looking forward to seeing how it works on some of our models! Nice work!  
-jd
The conflict is caused by:
    onnx-simplifier 0.3.7 depends on onnxoptimizer>=0.2.5
    onnx-simplifier 0.3.6 depends on onnxoptimizer>=0.2.5
    onnx-simplifier 0.3.5 depends on onnxoptimizer>=0.2.5
    onnx-simplifier 0.3.4 depends on onnxoptimizer>=0.2.5
    onnx-simplifier 0.3.3 depends on onnxoptimizer>=0.2.4
    onnx-simplifier 0.3.2 depends on onnxoptimizer>=0.2.3
    onnx-simplifier 0.3.1 depends on onnxoptimizer>=0.2.2
    onnx-simplifier 0.3.0 depends on onnxoptimizer>=0.2.0
    onnx-simplifier 0.2.28 depends on onnxoptimizer>=0.2.0
    onnx-simplifier 0.2.27 depends on onnxoptimizer>=0.2.0
    onnx-simplifier 0.2.26 depends on onnxoptimizer>=0.2.0
    onnx-simplifier 0.2.25 depends on onnxoptimizer>=0.2.0
    onnx-simplifier 0.2.24 depends on onnxoptimizer>=0.2.0
    onnx-simplifier 0.2.23 depends on onnxoptimizer>=0.2.0
    onnx-simplifier 0.2.22 depends on onnxoptimizer>=0.1.2
    onnx-simplifier 0.2.21 depends on onnxoptimizer>=0.1.2
    onnx-simplifier 0.2.20 depends on onnxoptimizer>=0.1.2
    onnx-simplifier 0.2.19 depends on onnxoptimizer>=0.1.1
    onnx-simplifier 0.2.18 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.17 depends on onnxoptimizer
    onnx-simplifier 0.2.16 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.15 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.14 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.13 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.12 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.11 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.10 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.9 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.8 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.7 depends on onnxruntime>=1.2.0
    onnx-simplifier 0.2.6 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.2.5 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.2.4 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.2.3 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.2.2 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.2.1 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.2.0 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.1.9 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.1.8 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.1.6 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.1.5 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.1.4 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.1.3 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.1.2 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.1.1 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.1.0 depends on onnxruntime>=0.3.0
    onnx-simplifier 0.0.0 depends on onnxruntime>=0.3.0

**Comment by daquexian** [comment]
Sorry for the late reply. Could you please try the [web version](https://convertmodel.com/#input=onnx&output=onnx) again?

**Comment by daquexian** [comment]
I'm closing this issue. Feel free to reopen it if you have further questions.
