### ISSUE TITLE
如何在优化后依然保持dynamic shape

### ISSUE THREAD

**Issue by deephog** [daquexian/onnx-simplifier#183]
你好，请问如果我的onnx模型在优化前如果是导出成dynamic shape（比如batch size是dynamic），我应该如何操作才能够保持优化后依然是dynamic shape 而不是成为fixed shape呢？谢谢！

**Comment by daquexian** [comment]
你好，你有试过 --dynamic-shape 这个命令行参数吗

**Comment by deephog** [comment]
> 你好，你有试过 --dynamic-shape 这个命令行参数吗

你好，感谢回复，我试过--dynamic-input-shape, 得到的错误信息是这样的：

The shape of input "image" has dynamic size "[0, 6, 720, 1280]", please determine the input size manually by "--dynamic-input-shape --input-shape xxx" or "--input-shape xxx". Run "python3 -m onnxsim -h" for details

似乎dynamic shape之后还是得跟一个具体的input shape，让我有一些疑惑，烦请大佬指点！谢谢

**Comment by HYL-Dave** [comment]
@deephog @daquexian 
我也有相同的問題和Error log

**Comment by daquexian** [comment]
@deephog @HYL-Dave 你们好！抱歉没有及时回复。开启 dynamic shape 后确实需要传入一个具体的 input shape，但它只是为了生成随机测试数据，不会覆盖原模型的 input shape。如果有新的问题欢迎继续回复！

**Comment by deephog** [comment]
> @deephog @HYL-Dave 你们好！抱歉没有及时回复。开启 dynamic shape 后确实需要传入一个具体的 input shape，但它只是为了生成随机测试数据，不会覆盖原模型的 input shape。如果有新的问题欢迎继续回复！

谢谢大佬指点！

**Comment by daquexian** [comment]
> > @deephog @HYL-Dave 你们好！抱歉没有及时回复。开启 dynamic shape 后确实需要传入一个具体的 input shape，但它只是为了生成随机测试数据，不会覆盖原模型的 input shape。如果有新的问题欢迎继续回复！
> 
> 谢谢大佬指点！

客气，那么这个 issue 就关掉了~ 有问题欢迎继续联系
