### ISSUE TITLE
torch.tensor.unfold can not be simplified

### ISSUE THREAD

**Issue by TingfengTang** [daquexian/onnx-simplifier#188]
Hi, there are some unfold Ops in my model, but torch.onnx.export can not handle it rightly:
![116342244-dcabf000-a814-11eb-81f7-237e7bf78228](https://user-images.githubusercontent.com/7879132/169553633-dbb4e578-88f2-4d6e-83d9-cabe8e034cbf.png)
So I use onnx-simplifier to simplify the model, but failed.
The code below will reproduce the result
```
import torch
import torch.nn as nn
import onnx
import onnxsim

class Unfold(nn.Module):
    def forward(self, x):
        return x.unfold(-1, 4, 2)

model = Unfold()

x = torch.arange(72).reshape(1, 3, 24).float()
y = model(x)
torch.onnx.export(
    model, x, 'model.onnx', verbose=False,
    input_names=['input'], output_names=['output']}, opset_version=11)
model_onnx=onnx.load('model.onnx')
model_simp, check =onnxsim.simplify(model_onnx)
assert check, "Simplified ONNX model could not be validated"
onnx.save(model_simp,'model_simp.onnx')
```

**Comment by daquexian** [comment]
Thanks for your report.

onnxsim can only simplify ops whose all inputs are constant, so it is expected that the model you demonstrated cannot be simplified. 

Feel free to reopen the issue if you have more questions.
