### ISSUE TITLE
[咨询] 请问下onnxsim支持多输入 dynamic shape吗

### ISSUE THREAD

**Issue by wjj19950828** [daquexian/onnx-simplifier#189]
**Describe the bug**
如果是多输入的话，动态shape应该如何使用呢

单输入：
```shell
python -m onnxsim --dynamic-input-shape --input-shape="input_ids:1,10" model.onnx model_sim.onnx 
```

多输入尝试了好几种都不太行

感谢～

**Comment by daquexian** [comment]
你好，可以在网页版 convertmodel.com/#input=onnx&output=onnx 上试一下吗

**Comment by wjj19950828** [comment]
@daquexian 您好，好像都会报错

没有命令行可以支持吗

**Comment by hermosayhl** [comment]
> 

请问开发好了吗？我也遇到了这个问题，部分动态输入，部分又是固定输入

**Comment by zhangjiefeng** [comment]
using the format below:

python3 -m onnxsim original.onnx dest_sim.onnx --input-shape input1_name:num1,num2,num3 input2_name:num4,num5
