### ISSUE TITLE
Detection Output Op crash

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [daquexian/onnx-simplifier#192]
**Describe the bug**
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for DetectionOutput with domain_version of 11

**Model**
https://disk.yandex.ru/d/-NX7YHbHvBxSrw

**Comment by HSQ79815** [comment]
@Yrij-Zhavoronkov `DetectionOutput` is a custom op in your model, but it's domain is empty that implies the operator set that is defined as part of  the onnx specification. So You should  set the domain of `DetectionOutput` by manual:

```python
import onnx
import onnx.helper as helper
import onnx.checker as checker

custom_domain = "Custom"

model = onnx.load("dpe_552_human_ssd_30k_cpu.onnx.onnx")
for node in model.graph.node:
    if node.op_type == "DetectionOutput":
        node.domain = custom_domain

model.opset_import.append(helper.make_operatorsetid(custom_domain, 1))
checker.check_model(model)
```
