### ISSUE TITLE
What models does it support

### ISSUE THREAD

**Issue by kadirnar** [daquexian/onnx-simplifier#193]
Why should we choose this repo? Does it support Yolo models?

**Comment by daquexian** [comment]
Sorry for the late reply.

All ONNX models are supported. For example, [yolov5](https://github.com/ultralytics/yolov5/blob/fbe67e465375231474a2ad80a4389efc77ecff99/export.py#L153) officially uses onnxsim to simplify its models.

**Comment by kadirnar** [comment]
Does it work in yolox, yolov6 and Yolov7 models?

**Comment by daquexian** [comment]
> Does it work in yolox, yolov6 and Yolov7 models?

I think yes. Indeed, yolox also officially uses onnxsim

**Comment by kadirnar** [comment]
This is great. I would like to add this repo to the [SAHI](https://github.com/obss/sahi) repo. Can you share sample documentation for me to write prediction codes?

https://github.com/obss/sahi/blob/main/sahi/model.py#L372-L513

**Comment by daquexian** [comment]
> Can you share sample documentation for me to write prediction codes?

Sorry for the late response. Using onnxsim is so easy, you can follow the code of yolov5: https://github.com/ultralytics/yolov5/blob/1c5e92aba11f0dd007716821e7cd151d532342a8/export.py#L152-L164
