### ISSUE TITLE
[BUG] Handling Loop operator without loop carried dependencies

### ISSUE THREAD

**Issue by gyenesvi** [daquexian/onnx-simplifier#204]
**Describe the bug**

I suspect that the `Loop` operator has a special case that is not handled properly by the simplifier. According to the ONNX [documentation](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Loop), the operator has 2+n inputs where n is the number of loop carried dependencies, and the inputs are 1) the initial condition, 2) the trip count, and the rest is the initial values for the n loop carried dependencies. The special case is when n=0, i.e. there are no loop carried dependencies and the loop is purely parallel, such as when looping across the batch dimension. Furthermore, the first 2 inputs to the operator may be constants (typically true for the initial condition, and the trip count may be constant such as the batch size), in which case the loop operator has only 2 constant inputs, hence it becomes disconnected from the rest of the graph and the optimizer splits the graph after the constant inputs are evaluated. What the optimizer does not seem to take into account is that the sub-graph describing the body of the loop may use any tensors from the outer scope, and those are not listed as inputs to the loop operator itself (by definition of the ONNX `Loop` operator, which I believe is a dangerous construct as it complicates processing of such graphs). So such a loop operator is not disconnected from the rest of the graph because it contains hidden connections to it.

**Model**

[Here](https://zenodo.org/record/4735652/files/ssd_mobilenet_v1_coco_2018_01_28.onnx) is an SSD mobilenet that was used in MLPerf that exhibits the problem.

**Comment by daquexian** [comment]
> So such a loop operator is not disconnected from the rest of the graph because it contains hidden connections to it.

Thanks for your report! You are right, however, I think onnxsim does skip the operators with subgraph attributes (like Loop, If, and maybe other operators) [here](https://github.com/daquexian/onnx-simplifier/blob/6509dfeb73c44bf3092c8d21a326e2b68ba38a3f/onnxsim/onnxsim.cpp#L341). Do you meet problems (the output value changes after simplifying) on this SSD mobilenet model?

**Comment by gyenesvi** [comment]
By skipping, do you mean that it's not effected by simplification? So it should not change?
What I have observed is that the graph after optimization, when opened in Netron viewer, looks different than before; it seemed disconnected from the rest of the graph, but maybe it's just Netron viewer that does not handle this operation well, not taking it's hidden inputs into account.

This issue report (in MLPerf repo) contains some screenshots showing the problem:
https://github.com/mlcommons/inference/issues/1125

But now I believe I start to understand what's happening here. In the original graph, the loop has an input, the loop count, which is derived from a tensors's shape. The optimization evaluates that shape to a constant, hence the loop count becomes a constant as well, and the loop operator will not have any visible non-constant inputs. That is why Netron shows it differently, moving the loop node to the beginning of the graph, and showing it detached, when in reality it has hidden inputs.
Do you believe that is a realistic explanation?

**Comment by daquexian** [comment]
> Do you believe that is a realistic explanation?

I agree. I believe it is an issue of netron.
