### ISSUE TITLE
onnx ShapeInferenceError when using onnxsim

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [daquexian/onnx-simplifier#209]
**Describe the bug**
1、paddle2onnx导出ppyoloe模型的onnx文件
2、使用onnxsim优化前述onnx模型，报错onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: Gather_12): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 0: (1) vs (-1)
3、使用paddle2onnx.optimize制定input shape，无效

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

**Comment by aureosun** [comment]
@MoonBunnyZZZ 您那边怎么解决这个问题的，求教，我遇到类似的问题

**Comment by daquexian** [comment]
> @MoonBunnyZZZ 您那边怎么解决这个问题的，求教，我遇到类似的问题

可以把模型发给我 daquexian566@gmail.com ，或者加 qq/微信 群~
