### ISSUE TITLE
[BUG] Error occurs when simplifying onnx with custom op

### ISSUE THREAD

**Issue by nanmi** [daquexian/onnx-simplifier#210]
**Describe the bug**
Error occurs when simplifying onnx with custom op.
```shell
onnxsim ctdet_coco_dla_2x.onnx ctdet_coco_dla_2x_sim.onnx
Simplifying...
Traceback (most recent call last):
  File "/home/test/.local/bin/onnxsim", line 8, in <module>
    sys.exit(main())
  File "/home/test/.local/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 405, in main
    model_opt, check_ok = simplify(
  File "/home/test/.local/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 181, in simplify
    model_opt_bytes = C.simplify(
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for DCNv2_TRT with domain_version of 11

==> Context: Bad node spec for node. Name: Plugin_95 OpType: DCNv2_TRT
```
`onnx-simplifier == 0.4.3`
I'm not sure if it's a bug in pytorch exporting onnx or a bug in onnxsim.

**Model**
model for [gdrive](https://drive.google.com/file/d/1HlYGyK8HjF6GaElRwZIPdoVoRsjoXTD7/view?usp=sharing)

**Comment by daquexian** [comment]
Thanks for your report. Placing the custom op in custom domain instead of default domain may fix the problem.

Please feel free to reopen the issue if you have further questions.
