### ISSUE TITLE
[BUG] 0.4.3 后版本部分算子不会被折叠

### ISSUE THREAD

**Issue by Xyzhao1999** [daquexian/onnx-simplifier#212]
**Describe the bug**

测试中发现新版本中，如果提前使用 `onnx.shape_inference.infer_shapes` 给网络进行了尺度推导并出现了unk维度，网络中部分可折叠的层不再会被折叠

如下面的部分，提前做了`shape_inference`后，再调用`onnx.simplify`就不会被折叠了

![image](https://user-images.githubusercontent.com/23482405/181904343-6077c66a-25d4-4a6c-b991-788405c8c65e.png)

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

**Comment by Xyzhao1999** [comment]
嗯 似乎不是个bug 应该是我自己写的调用有一些问题。。。。直接使用onnxsim是OK 的

**Comment by daquexian** [comment]
感谢！确实是 bug，我这就修复

**Comment by daquexian** [comment]
你好，我又看了一下，刚刚想错了😂 方便把你出错的模型发给我吗，daquexian566@gmail.com 谢谢

**Comment by Xyzhao1999** [comment]
已发送邮件~

**Comment by daquexian** [comment]
你好，我测试了这个模型，不管是直接进行 onnxsim 还是先 infer_shapes 再 onnxsim，都是可以把所有的 ConstantOfShape、Expand、Tile op 消除掉的。可以把直接出问题的那个模型（也就是由你 infer_shapes 后的）发给我吗

**Comment by Xyzhao1999** [comment]
诶  这个模型就是问题模型啊😂  我测试一下相关的代码

**Comment by Xyzhao1999** [comment]
嗯 刚刚测试了一下 这个问题只在`0.4.3` 和 `0.4.4` 中出现。`0.4.5` 好像已经修复了😂


测试用代码
```python
import onnx
import onnxoptimizer
import onnxsim
from onnx.shape_inference import infer_shapes


ori_model = onnx.load('test_model.onnx')

sim_model, _ = onnxsim.simplify(ori_model)

print('sim_model_without_infer_shapes')
onnxsim.model_info.print_simplifying_info(ori_model, sim_model)

onnx.save_model(sim_model, 'sim_model_without_infer_shapes.onnx')


shape_model = onnx.shape_inference.infer_shapes(ori_model)
sim_shape_model, _ = onnxsim.simplify(shape_model)

print('sim_model_with_infer_shapes')
onnxsim.model_info.print_simplifying_info(ori_model, sim_shape_model)

onnx.save_model(sim_shape_model, 'sim_model_with_infer_shapes.onnx')
```

**Comment by daquexian** [comment]
哦哦如果确定的话可以关掉这个 issue 😉
