### ISSUE TITLE
if i use dynamic shape to onnxsim model,then the mode input shape will be fixed the  the input shape as i add  the praameters --input shape?

### ISSUE THREAD

**Issue by cqray1990** [daquexian/onnx-simplifier#213]
**Describe the bug**

**Model**
To reproduce the problem, please post download link of your model here, or send your model to daquexian566@gmail.com

if i use dynamic shape to onnxsim model,then the mode input shape will be fixed the  the input shape as i add  the praameters --input shape?

i find if use  --input-shape 1,1,32,600  even i convert onnx model with  dynamic_axes, the input will be fixed 1,1,32,600,and then iinference error with variable input  shape

errors:
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input for the following indices
 index: 3 Got: 146 Expected: 600
 Please fix either the inputs or the model.

**Comment by daquexian** [comment]
Thanks for your report! Please upgrade to the latest version so that --input-shape is not needed any more.
