### ISSUE TITLE
[BUG] Cannot simplify Stable Diffusion

### ISSUE THREAD

**Issue by FL33TW00D** [daquexian/onnx-simplifier#226]
**Describe the bug**
After exporting Stable Diffusion to ONNX as described in this [PR](https://github.com/huggingface/diffusers/pull/399) it would be great to simplify the model. When running the following command to simplify the `unet` model:
`onnxsim model.onnx unet.onnx`

```
Traceback (most recent call last):
  File "/.pyenv/versions/3.10.5/bin/onnxsim", line 8, in <module>
    sys.exit(main())
  File "/.pyenv/versions/3.10.5/lib/python3.10/site-packages/onnxsim/onnx_simplifier.py", line 429, in main
    model_opt, check_ok = simplify(
  File "/.pyenv/versions/3.10.5/lib/python3.10/site-packages/onnxsim/onnx_simplifier.py", line 183, in simplify
    model_opt_bytes = C.simplify(
RuntimeError: The model does not have an ir_version set properly.
```

I set the model `ir_version` manually to a few different versions to see if it made any change, but no luck. Any ideas here? The model has the ir_version set on the python side, but we fail on this [line](https://github.com/onnx/onnx/blob/d15ba967cfd2b7804634e0ffb03bdba8c1bc4527/onnx/checker.cc#L941).

**Comment by sanjay23singh** [comment]
Hey, @FL33TW00D did you get any solution?

**Comment by FL33TW00D** [comment]
@sanjay23singh Follow the guide here: https://www.photoroom.com/tech/stable-diffusion-25-percent-faster-and-save-seconds/

**Comment by electricazimuth** [comment]
This issue still persists, 
```
optimum-cli export onnx --model stable-diffusion-v1-5/stable-diffusion-v1-5 --task stable-diffusion --opset 14 --device cpu --optimize O1 --no-post-process
```
or ```torch.onnx.export(...``` will generate onnx files with no IR version. These models then can't be run, would be great if teh check could be switched off and the IR / OP set versions supplied on the command line
