### ISSUE TITLE
[BUG] Constant nodes with optional arguments not optimized away

### ISSUE THREAD

**Issue by aernoudt** [daquexian/onnx-simplifier#239]
Constant nodes that have an unspecified optional argument (empty string) are not optimized away.

[const_names](https://github.com/daquexian/onnx-simplifier/blob/master/onnxsim/onnxsim.cpp#L351) does not contain the empty string which means [onnxsim.cpp#L366](https://github.com/daquexian/onnx-simplifier/blob/master/onnxsim/onnxsim.cpp#L366) will return false if the inputs of a constant node has an unspecified optional argument (empty string)

Test for constant Resize node with constant inputs and unspecified optional arguments:
[testONNXSim.py.txt](https://github.com/daquexian/onnx-simplifier/files/9931142/testONNXSim.py.txt)

**Comment by aernoudt** [comment]
Any updated on this?

**Comment by daquexian** [comment]
sorry for the delay. I'll look at it tomorrow

**Comment by daquexian** [comment]
@aernoudt It has been fixed in the master branch and the new version v0.4.25 will be published about two hours later. Please feel free if you have any further questions. Thanks for your report!
