### ISSUE TITLE
[BUG] onnxsim simplifies pad + average pool into a single average pool without handling the pad border mode correctly

### ISSUE THREAD

**Issue by rbonhamcarter** [daquexian/onnx-simplifier#244]
**Describe the bug**
When passing a model containing just a Pad layer (with border==constant) followed by an Average Pooling layer (with no padding), `onnxsim` simplifies by replacing the two layers (Pad & Average Pool) with a single Average Pool with non-zero padding, but the `count_include_pad` attribute is not used, which results in the border mode being set to the default for the ONNX implementation of Average Pool. The default is to set `count_include_pad=0` which is equivalent to using border==ignore instead of border==constant. 
As such, the output of the model before and after `onnxsim` was used are not the same. 

There are two possible fixes for this issue that I could think of:

1. Do not fold Pad and Average Pool operations together
2. Set the `count_include_pad` attribute of the Average Pool layer according to the border mode of the Pad layer that is being folded into it.

**Model**
I have attached a zip file containing two minimal model files to aid in replicating this issue:

- `model.onnx` is the original model file to be passed as input to `onnxsim`
- `model_simplified.onnx` is the result I obtained by running `model.onnx` through `onnxsim`

[models.zip](https://github.com/daquexian/onnx-simplifier/files/10117584/models.zip)

**Comment by rbonhamcarter** [comment]
If you have any suggestions for how to fix this bug I'd be happy to implement a fix and submit a PR.

**Comment by daquexian** [comment]
Thanks for your report! I'll reply it tomorrow

**Comment by HarmonyHu** [comment]
> Thanks for your report! I'll reply it tomorrow

@daquexian Has this issue been fixed in new version ? I also encountered this problem.

**Comment by rbonhamcarter** [comment]
@daquexian Any updates on resolving this issue? 

If the bug is still around in the newest version, I'm still happy to work on a fix and submit a PR if that's preferable.

**Comment by daquexian** [comment]
@rbonhamcarter Sorry for the late response. It has been fixed in the latest version thanks to @HarmonyHu's PR https://github.com/onnx/optimizer/pull/108
