### ISSUE TITLE
[BUG] Operators not be simplified after custom op

### ISSUE THREAD

**Issue by BinMatrix** [daquexian/onnx-simplifier#246]
**Describe the bug**
I found that if there has a custom operator, such as dcn, the operators after this custom operator will be not simplified.

No dcn:
![no_dcn](https://user-images.githubusercontent.com/8712304/205631216-d885fa6c-d968-4a18-a38d-1f607e6be4a1.png)

Have dcn:
![dcn](https://user-images.githubusercontent.com/8712304/205631266-dcfe614a-35f9-4875-91d3-d422acd82934.png)

And I notice that the shape inference stop at the first custom op:
![image](https://user-images.githubusercontent.com/8712304/205632648-0ca74b37-66cc-4c1d-ab9a-ecf9ff01a42f.png)

Is the shape inference failure caused this problem? And how to make the shape inference and the simplifier work for custom op?

**Model**
[download this model](https://drive.google.com/file/d/1zGNRRR1xs7Lky6eNm-OFMI5nmEWIPbOa/view?usp=sharing)

**Comment by daquexian** [comment]
> Is the shape inference failure caused this problem?

Yes

> And how to make the shape inference and the simplifier work for custom op?

It is kind of complicated. The shape inference functionality must be implemented in C++. Maybe in the future I can implement the shape inference of the most common custom ops and ship them within onnxsim.

**Comment by BinMatrix** [comment]
Thanks for your reply!
I found a simple way to make it work, only for static shape model.

1. Use summary tool to show shape info of all layers, so you can get every custom op output shape by its next layer. I use pytorch_model_summary, other summary tool (such as torchsummary, but not work for my complex model) or other way also OK.
```python
from pytorch_model_summary import summary
summary(model, *dummy, print_summary=True, max_depth=None, show_parent_layers=True)
```

2. Add the custom op output shape got from first step to the onnx model. like this:
```python
# shape inference will stop at custom op, and lead to simplifier stop,
# so need add output shape of custom op before simplifier
def add_custom_op_shape(onnx_model):
    for node in onnx_model.graph.node:
        # add shape for dcn
        if node.op_type == 'MMCVModulatedDeformConv2d':
            shape_info = helper.make_tensor_value_info(node.output[0], TensorProto.FLOAT, [5, 256, 34, 60])
            onnx_model.graph.value_info.append(shape_info)
        # add shape for other custom op
```

3. Simplify the onnx model by onnxsim. Because the custom op has already output shape, the simplifier will continue to the end.
