### ISSUE TITLE
[BUG] 目前最新版本似乎无法处理动态输入和动态输出

### ISSUE THREAD

**Issue by wzyforgit** [daquexian/onnx-simplifier#247]
1.从pypi拉取最新的onnxsim
2.尝试对以下模型进行简化，命令：onnxsim rec_ch.onnx sim_rec_ch.onnx --overwrite-input-sharp 1,3,32,100
3.报告最后的sharp没有对齐？一个 -1 一个 1

ps: 大版本更新前的是可以正确简化的，目前网页那边由于无法指定输入sharp，只能转一半，最后会剩两个sharp算子无法消除

模型：
[rec_ch.zip](https://github.com/daquexian/onnx-simplifier/files/10203829/rec_ch.zip)

**Comment by daquexian** [comment]
抱歉回复晚了。我猜这个模型是 paddle 导出的？paddle2onnx 曾经错误地用 -1 来表示动态形状，现在已经修复了 https://github.com/PaddlePaddle/Paddle2ONNX/issues/928 。可以考虑用最新的 paddle2onnx 试下
