### ISSUE TITLE
[Feature Request] Add LayerNormalization (since opset 17) and the fusion for it

### ISSUE THREAD

**Issue by fengyuentau** [daquexian/onnx-simplifier#252]
LayerNormalization is added since ONNX opset 17. LayerNormalization looks like the following in expanded form (right side) vs LayerNormalization (left side):

```mermaid
stateDiagram-v2
reducemean1: ReduceMean
pow1: Pow(Y=2)
add1: Add(B=1e-5)
mul1: Mul(B=Const.weight)
add2: Add(B=Const.bias)
anotherX: X
anotherY: Y

X --> ReduceMean
X --> Sub
ReduceMean --> Sub
Sub --> Div
Sub --> pow1
pow1 --> reducemean1
reducemean1 --> add1
add1 --> Sqrt
Sqrt --> Div
Div --> mul1
mul1 --> add2
add2 --> Y


anotherX --> LayerNormalization
LayerNormalization --> anotherY
```

Latest PyTorch has supported exporting ONNX of opset>=17. The current version of onnx-simplifier cannot simplify ViT models exported from PyTorch with opset>=17, resulting in the following error:

```shell
$ onnxsim vit_16_b.onnx
Traceback (most recent call last):
  #...
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for LayerNormalization with domain_version of 17

==> Context: Bad node spec for node. Name: /encoder/layers/encoder_layer_0/ln_1/LayerNormalization OpType: LayerNormalization
```

I would like to make a pull request for this feature if applicable.

---

Note: You could generate ONNX ViT with the latest PyTorch and TorchVision:

```python
import torch
import torchvision

dummy_input = torch.randn(1, 3, 224, 224, device="cpu")
input_names = [ "input" ]
output_names = [ "output" ]

model = torchvision.models.vit_b_16(weights=torchvision.models.ViT_B_16_Weights.DEFAULT)
torch.onnx.export(model, dummy_input, "vit_b_16.opset17.onnx", verbose=False, export_params=True,
                  opset_version=17, input_names=input_names, output_names=output_names)
torch.onnx.export(model, dummy_input, "vit_b_16.opset11.onnx", verbose=False, export_params=True,
                  opset_version=11, input_names=input_names, output_names=output_names)

```

**Comment by daquexian** [comment]
Thanks for your issue! Could you please install the latest onnxruntime and try again? 

By the "fusion" do you mean fuse the ops on the right side of your image to the left side? If so you might want to add a pass to onnx/optimizer repo, where all graph optimization are implemented.

BTW, it is highly recommended to join our ONNX wechat or QQ group for smooth communication. My ID is daquexian on both apps.

**Comment by fengyuentau** [comment]
Thank you for the quick response! My onnxruntime version is 1.13.1 which is the latest I think. I made this issue especially for the onnx parser and simplifier that we maintain in OpenCV dnn. Your work helps us a lot. Thank you!

> By the "fusion" do you mean fuse the ops on the right side of your image to the left side?

Yes, I mean this. Does onnx-simplifier and onnxruntime now use onnx/optimizer as backend for graph optimization? I found onnxruntime have the same inference performance regardless layer norm expanded or not.

---

I will join the ONNX QQ group by the way. Could we continue our talk in this issue until it is closed?

**Comment by fengyuentau** [comment]
I just looked into the code and found the error

```
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for LayerNormalization with domain_version of 17
```

was actually from onnx/onnx checker:

https://github.com/daquexian/onnx/blob/bd6946528c25d0038c1f518b9826a9a1582fd4c0/onnx/checker.cc#L634

However, it looks weird to me that `OpSet_Onnx_ver17` was already registered in `operator_sets.h` in your fork but the checker still complains LayerNormalization not found. Good news is I found how to fuse those operators into one single LayerNormalization in onnx/optimizer:onnxoptimizer/passes.
