### ISSUE TITLE
[BUG] Model only 78 kb after simplification

### ISSUE THREAD

**Issue by MrMaynard** [daquexian/onnx-simplifier#271]
**Describe the bug**

When I simplify my model, it results in a very small file. This file can not be read by TensorRT.

I created this ONNX using the latest onnxsim:
```
import onnx
from onnxsim import simplify

model = onnx.load("bin/minified.onnx")
model_simp, check = simplify(model)
onnx.save(model_simp, "bin/minified_simplified.onnx")
```

When I try to convert it to TensorRT like so:
```
trtexec --onnx=bin/minified_simplified.onnx --saveEngine=bin/minified_simplified.engine
```

This fails:
```
[6] Assertion failed: (splitList.empty() || (splitList.size() == numOutputs)) && "The shape of the split attribute misaligns with the number of outputs."
```

This is my model:
[minified.zip](https://github.com/daquexian/onnx-simplifier/files/11186157/minified.zip)

And this is the result of simplification:

[minified_simplified.zip](https://github.com/daquexian/onnx-simplifier/files/11186158/minified_simplified.zip)

**Comment by daquexian** [comment]
The bug is fixed in version 0.4.21. Please have a try and feel free to reopen this issue if you have any further questions.
