### ISSUE TITLE
onnx模型转换出错：ParseTensorData: Assertion `elem_cnt == (raw_data_size / sizeof(int64_t))` failed.

### ISSUE THREAD

**Issue by yangji307** [daquexian/onnx-simplifier#273]
使用onnx.checker.check_model检验模型通过了，同时使用onnxruntime也可以正常运行，就是在简化模型的时候报错：
D:\a\onnx-simplifier\onnx-simplifier\third_party\onnx-optimizer\onnxoptimizer\passes\tensor_util.cc:74: ParseTensorData: Assertion `elem_cnt == (raw_data_size / sizeof(int64_t))` failed.
请求大佬帮助！
这是我所测试的模型：https://pan.quark.cn/s/e4fccccfb479

**Comment by hhhhpaaa** [comment]
I'm also having this issue, but I don't know how to solve it.
Simplifying with onnx-simplifier 0.4.19.
Traceback (most recent call last):
  File "C:\Users\c2793\.conda\envs\pytorch\lib\site-packages\onnxsim\onnx_simplifier.py", line 186, in simplify
    model_opt_bytes = C.simplify(
RuntimeError: D:\a\onnx-simplifier\onnx-simplifier\third_party\onnx-optimizer\onnxoptimizer\passes\tensor_util.cc:74: ParseTensorData: Assertion `elem_cnt == (raw_data_size / sizeof(int64_t))` failed.

**Comment by yangji307** [comment]
i have not solve this problem yet,  any idea already?

> I'm also having this issue, but I don't know how to solve it. Simplifying with onnx-simplifier 0.4.19. Traceback (most recent call last): File "C:\Users\c2793.conda\envs\pytorch\lib\site-packages\onnxsim\onnx_simplifier.py", line 186, in simplify model_opt_bytes = C.simplify( RuntimeError: D:\a\onnx-simplifier\onnx-simplifier\third_party\onnx-optimizer\onnxoptimizer\passes\tensor_util.cc:74: ParseTensorData: Assertion `elem_cnt == (raw_data_size / sizeof(int64_t))` failed.

**Comment by yangji307** [comment]
> I'm also having this issue, but I don't know how to solve it. Simplifying with onnx-simplifier 0.4.19. Traceback (most recent call last): File "C:\Users\c2793.conda\envs\pytorch\lib\site-packages\onnxsim\onnx_simplifier.py", line 186, in simplify model_opt_bytes = C.simplify( RuntimeError: D:\a\onnx-simplifier\onnx-simplifier\third_party\onnx-optimizer\onnxoptimizer\passes\tensor_util.cc:74: ParseTensorData: Assertion `elem_cnt == (raw_data_size / sizeof(int64_t))` failed.

i successfully simplify onnx model on linux, you can try this method

**Comment by hhhhpaaa** [comment]
> > I'm also having this issue, but I don't know how to solve it. Simplifying with onnx-simplifier 0.4.19. Traceback (most recent call last): File "C:\Users\c2793.conda\envs\pytorch\lib\site-packages\onnxsim\onnx_simplifier.py", line 186, in simplify model_opt_bytes = C.simplify( RuntimeError: D:\a\onnx-simplifier\onnx-simplifier\third_party\onnx-optimizer\onnxoptimizer\passes\tensor_util.cc:74: ParseTensorData: Assertion `elem_cnt == (raw_data_size / sizeof(int64_t))` failed.
> 
> i successfully simplify onnx model on linux, you can try this method

Thanks. This is a good idea. In Ubuntu, it works.

**Comment by daquexian** [comment]
@yangji307 Could you please try the latest 0.4.22 version? Thanks!

**Comment by hhhhpaaa** [comment]
> @yangji307 Could you please try the latest 0.4.22 version? Thanks!

I try to use the latest 0.4.22 version to simplify my onnx model on Windows 11. It works well！This issue is fixed in the latest version.  Many thanks.

**Comment by daquexian** [comment]
> > @yangji307 Could you please try the latest 0.4.22 version? Thanks!
> 
> I try to use the latest 0.4.22 version to simplify my onnx model on Windows 11. It works well！This issue is fixed in the latest version. Many thanks.

Glad to hear that :)

**Comment by yangyf137c** [comment]
是的！采用了新版本的onnx-simplifier就没有这个问题了，非常感谢！
