### ISSUE TITLE
[BUG] Cannot be folded constant

### ISSUE THREAD

**Issue by OYCN** [daquexian/onnx-simplifier#281]
**Describe the bug**

Maybe the onnx was not be folded?

![middle_img_v2_2897f1f3-8dd4-4c67-89cf-5aae899f6f8l](https://user-images.githubusercontent.com/34306806/235091057-e7fd7f2e-cd91-49ca-a4a2-16b99342b79c.png)

**Model**

input onnx:
[io.zip](https://github.com/daquexian/onnx-simplifier/files/11351344/io.zip)

pytorch code:
```
import torch
import torch.nn as nn
import torch.nn.functional as F

class T(nn.Module):
  def __init__(self, *args, **kwargs) -> None:
    super().__init__(*args, **kwargs)
    self.const0 = nn.Parameter(torch.rand(4, 1))
    self.const1 = nn.Parameter(torch.rand(4, 64))
  
  def forward(self, x):
    const0_clip = torch.clip(self.const0, min=9.999999960041972e-13)
    const0_clip_expand = const0_clip.expand_as(self.const1)
    const0_clip_expand_div_const1 = const0_clip_expand / self.const1
    const0_clip_expand_div_const1_reshape = const0_clip_expand_div_const1.reshape(4, 64, 1, 1)
    out = F.conv2d(x, const0_clip_expand_div_const1_reshape, stride=1, padding=0, groups=1, dilation=1)
    return out
  
t = T()
t.eval()
torch.onnx.export(t, torch.rand(1, 64, 32, 32), './t.onnx', verbose=False, opset_version=11, input_names=['input'], output_names=['output'])
```

**Comment by OYCN** [comment]
It seems like `max` in Clip named a empty string and it was not be assumed a constant. Is empty name considered actual data in onnx? @daquexian

**Comment by daquexian** [comment]
reference: https://github.com/daquexian/onnx-simplifier/issues/239

I'll fix it soon

**Comment by OYCN** [comment]
Thanks!
I will follow it and close this issue.
