### ISSUE TITLE
[BUG] onnx/common/ir.h:642: insertAfter: Assertion !inGraphList() && n->inGraphList() failed.

### ISSUE THREAD

**Issue by luchangli03** [daquexian/onnx-simplifier#284]
**Describe the bug**
Simplifying...
Traceback (most recent call last):
  File "/root/miniconda3/envs/lite/bin/onnxsim", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/lite/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 481, in main
    model_opt, check_ok = simplify(
  File "/root/miniconda3/envs/lite/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 199, in simplify
    model_opt_bytes = C.simplify(
RuntimeError: /project/third_party/onnx-optimizer/third_party/onnx/onnx/common/ir.h:642: insertAfter: Assertion `!inGraphList() && n->inGraphList()` failed.

**Model**
I have a model, onnx.checker.check_model no problem, and can be infered by onnxruntime, but when optimized by onnxsim, give above error.

**Comment by Ruanzhh** [comment]
I encountered the same issue. May I ask how you solved this problem?

**Comment by luchangli03** [comment]
please try disable fuse qkv pass. this fusion only support merge 3 matmuls.



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/02/2023 16:32 |
| To | ***@***.***> |
| Cc | Luchang ***@***.***>、State ***@***.***> |
| Subject | Re: [daquexian/onnx-simplifier] [BUG] onnx/common/ir.h:642: insertAfter: Assertion !inGraphList() && n->inGraphList() failed. (Issue #284) |

I encountered the same issue. May I ask how you solved this problem?

**Comment by Ruanzhh** [comment]
Thanks for your kind reply :）

Luchang Li ***@***.***> 于2023年11月2日周四 21:17写道：
