### ISSUE TITLE
Not all data was converted

### ISSUE THREAD

**Issue by marooncn** [daquexian/onnx-simplifier#29]
Hi, I want to transfer onnx model to tensorrt model, but in the original generated onnx model, there are gather operation which is not supported. So I try to use onnx-simplifier to generate the corresponding onnx model, but there is an error:

> Not all data was converted
> google.protobuf.message.DecodeError: Protobuf decoding consumed too few bytes: 5 out of 50190117

It seems that if I use original onnx that I will get gather operation and if I use onnx-simplifier that I can't convert all data. Do you have any advice?

**Comment by daquexian** [comment]
Thanks for your report! Could you please send your model to daquexian566@gmail.com? Thanks!

**Comment by marooncn** [comment]
BTW, my model is [BiSeNet](https://drive.google.com/file/d/1ulUgHwFct-vFwGCAfJ4Oa9DBlNDzm5r4/view).

**Comment by daquexian** [comment]
> My model is [BiSeNet](https://drive.google.com/file/d/1ulUgHwFct-vFwGCAfJ4Oa9DBlNDzm5r4/view). You can download from the link, thank you.

It is pytorch model. Could you please send your onnx model to me?

**Comment by marooncn** [comment]
the onnx model converted by onnx-simplifier is not successful, the model converted by original onnx is on the another desktop, I'll send you tomorrow morning if you need.

**Comment by daquexian** [comment]
> the onnx model converted by onnx-simplifier is not successful, the model converted by original onnx is on the another desktop, I'll send you tomorrow morning if you need.

Yes, what I want is the original onnx. Thanks.

**Comment by daquexian** [comment]
I think you are using onnx-simplifier in the wrong way. You should first export an onnx model and then simplify your **onnx model** by using onnx-simplifier, so the command you should use is

```bash
python3 -m onnxsim BiSetNet.onnx new_model.onnx
```

but not

```bash
python3 -m onnxsim best_xxxx.pth new_model.onnx
```

However, the conversion fails due to https://github.com/daquexian/onnx-simplifier/issues/25, which is an another story :|

**Comment by marooncn** [comment]
Hi, @daquexian 
I do as  #25 to generate .onnx file using pytorch1.2, but I got another error:

> RuntimeError: Method run failed due to: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (N11onnxruntime11NonOnnxTypeIfEE) , expected: (N11onnxruntime11NonOnnxTypeINS_9MLFloat16EEE)

Do you have any suggestion to solve it? thank you.

**Comment by marooncn** [comment]
Fix it!
I just uncomment the _.cuda()_ and _.half()_ of the model and input.

> model = BiSeNet(13, 'resnet18').eval()  # .cuda().half().eval()
> model.load_state_dict(torch.load('./checkpoints_18_sgd/best_dice_loss_13_class.pth'))
> x = torch.ones((1, 3, 720, 960))  # .cuda().half()

**Comment by daquexian** [comment]
> Fix it!
> I just uncomment the _.cuda()_ and _.half()_ of the model and input.
> 
> > model = BiSeNet(13, 'resnet18').eval()  # .cuda().half().eval()
> > model.load_state_dict(torch.load('./checkpoints_18_sgd/best_dice_loss_13_class.pth'))
> > x = torch.ones((1, 3, 720, 960))  # .cuda().half()

Perfect! Congratulations!
