### ISSUE TITLE
KeyError: '271'  when simplifying SSD based face detection onnx model 

### ISSUE THREAD

**Issue by zxDeepDiver** [daquexian/onnx-simplifier#3]
Hi, 

I am using the **onnx-simplifier** to process the SSD onnx model. The model is originally from pytorch. I convert it from pytorch to onnx using `torch.onnx._export`. Then I use `python -m onnxsim faceboxes.onnx faceboxes-sim.onnx` to simplify the onnx model, and get the following error:

![image](https://user-images.githubusercontent.com/7352077/57455836-a8913a80-729e-11e9-8d56-64d8b42daf90.png)

The original pytorch code is : https://github.com/zisianw/FaceBoxes.PyTorch
The original pytorch model file (save with all information: "`torch.save(model,'model_all.pkl')`") is uploaded to the BaiduNetDisk.
The onnx file converted from pytorch model is also uploaded.

Model file address: 链接：https://pan.baidu.com/s/1HA-ONKXtRrxa6v5cDlL5UQ 
提取码：arrs 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by daquexian** [comment]
Thanks for your report. I will manage to solve it when I have time. :)

**Comment by daquexian** [comment]
Fixed in 502ef40. Please upgrade onnx-simplifier to 0.1.4

**Comment by daquexian** [comment]
Before:
![image](https://user-images.githubusercontent.com/11607199/57564084-f4e09580-73d8-11e9-9740-a8f73ca04536.png)
After:
![image](https://user-images.githubusercontent.com/11607199/57564107-3bce8b00-73d9-11e9-9808-22978ff1722a.png)
