### ISSUE TITLE
[BUG] Gather not supported yet!

### ISSUE THREAD

**Issue by RubyChenYR** [daquexian/onnx-simplifier#30]
I use onnx-simplifier to get a mynet-sim.onnx
but when I use onnx2ncnn to convert mynet-sim.onnx, it still says that:
Gather not supported yet!
  # axis=1
Gather not supported yet!
  # axis=1
Gather not supported yet!
  # axis=1

**Comment by daquexian** [comment]
onnx-simplifier doesn't guarantee to eliminate all gather ops. They will be eliminated only if its input is constant value

**Comment by nihui** [comment]
@daquexian  大佬，Gather 有可能优化成 Split 吗？我看有 shufflenet v2 用多个 Gather 模拟了 Split ....
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Split

**Comment by daquexian** [comment]
> @daquexian 大佬，Gather 有可能优化成 Split 吗？我看有 shufflenet v2 用多个 Gather 模拟了 Split ....
> https://github.com/onnx/onnx/blob/master/docs/Operators.md#Split

太可怕了，up 主有模型文件或者链接吗

**Comment by nihui** [comment]
onnx2ncnn 把这个转换做掉了

https://github.com/Tencent/ncnn/issues/1850
