### ISSUE TITLE
[BUG] About the ONNX concat order

### ISSUE THREAD

**Issue by muzi2045** [daquexian/onnx-simplifier#31]
**Describe the bug**
when the onnx-simplier simplify the onnx model, the operater concat order look like will be change, and it will leading data dimension different original pytorch dimension.

here is the original onnx model structure and the simplified onnx model:

![image](https://user-images.githubusercontent.com/12984898/68282676-07e8cf80-00b5-11ea-8e49-448fc339ff9c.png)
![image](https://user-images.githubusercontent.com/12984898/68282698-1636eb80-00b5-11ea-8b02-bc6dd36db25f.png)

**Comment by daquexian** [comment]
Thanks for your issue! However, onnxsim won't change the order of inputs. Could you please check the order once more in the right panel (like following)?

![image](https://user-images.githubusercontent.com/11607199/68284191-f48b3380-00b7-11ea-8317-76b000e82b2e.png)

**Comment by daquexian** [comment]
It turns out a bug of ONNX optimizer, https://github.com/onnx/onnx/issues/2436.

**Comment by daquexian** [comment]
The new onnxsim will not call this optimizer. However, I'd like to remain this issue open until it is fixed completely

**Comment by daquexian** [comment]
A fix from myself: https://github.com/onnx/onnx/pull/2447

**Comment by daquexian** [comment]
https://github.com/onnx/onnx/pull/2447 is merged. This issue will be closed when onnx 1.7 is released.

**Comment by daquexian** [comment]
ONNX 1.7 has been delayed much much much a lot. This issue is solved in web version: convertmodel.com, which is compiled from the updated onnx code.
