### ISSUE TITLE
为什么经过onnx-simplifier以后BatchNorm层都不见了

### ISSUE THREAD

**Issue by ItchyHiker** [daquexian/onnx-simplifier#36]
如题，我的模型经过onnx-simplifier简化之后BatchNorm层都没了

**Comment by daquexian** [comment]
因为它们被 onnx optimizer 优化掉了，不想这样的话可以指定这个参数 https://github.com/daquexian/onnx-simplifier/blob/master/onnxsim/__main__.py#L13

**Comment by ItchyHiker** [comment]
你好，再请问下为什么会被优化掉，一般的网络结构不是都会有batchnorm layer嘛？

**Comment by daquexian** [comment]
conv->bn 这种结构可以合并成一个 conv。在 onnx optimizer 里也有这个功能，onnxsim 默认会调用 onnx optimizer，所以 bn 被和 conv 合并了

**Comment by ItchyHiker** [comment]
好的，懂了，谢谢大佬！

**Comment by daquexian** [comment]
> 好的，懂了，谢谢大佬！

客气了 :)

**Comment by nihui** [comment]
大佬！

**Comment by sky186** [comment]
@daquexian 
您好作者，我想请问这里代码里有 bn合并到conv  , 有 bn 合并到fc 的简化操作吗

**Comment by daquexian** [comment]
> 您好作者，我想请问这里代码里有 bn合并到conv , 有 bn 合并到fc 的简化操作吗

@sky186 没有的，这个属于 onnx optimizer 的职责（它也是我维护的项目），可以在 https://github.com/onnx/optimizer 这个仓库里提交 issue

**Comment by sky186** [comment]
@daquexian 
好的，谢谢您，我已经提交了一个issue
