### ISSUE TITLE
ONNXruntimeError：could not find an implementation for the node BatchNormalization（6）？？

### ISSUE THREAD

**Issue by xugangtongji** [daquexian/onnx-simplifier#4]

**Comment by xugangtongji** [comment]
I had transferred “hourglass pytorch model”  to onnx，  then ncnn， but  i failed  in step onnx2ncnn

**Comment by daquexian** [comment]
Thanks for your report
Could you please provide your onnx model? thanks!

**Comment by xugangtongji** [comment]
Thank u a lot. I try to convert pytorch model to ncnn. follow by https://github.com/Tencent/ncnn/wiki/practical-pytorch-to-onnx-to-ncnn

I train model using this code. 
https://github.com/raymon-tian/hourglass-facekeypoints-detection
in the file "weights",there is pythorch model.

**Comment by daquexian** [comment]
@xugangtongji Do you have the onnx model? You can send me it by email, daquexian566@gmail.com

**Comment by i-amgeek** [comment]
Any update in this issue? I am facing similar problem but with PRelu.

`RuntimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node PRelu(6).`

**Comment by daquexian** [comment]
@xugangtongji Sorry, the mode is expired, could you send me again?

**Comment by daquexian** [comment]
@xugangtongji @i-amgeek Thanks for your report! Could you please send your model to daquexian566@gmail.com?

**Comment by i-amgeek** [comment]
> @xugangtongji @i-amgeek Thanks for your report! Could you please send your model to [daquexian566@gmail.com](mailto:daquexian566@gmail.com)?

Mailed.

**Comment by westpilgrim** [comment]
RuntimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Add(6)

**Comment by westpilgrim** [comment]
model mailed
