### ISSUE TITLE
Output mismatch between pytorch and onnx

### ISSUE THREAD

**Issue by sathiez** [daquexian/onnx-simplifier#41]
Hi,

I converted pytorch (.pt) model to onnx using torch.onnx.export, during inference first four values which is bbox values are different and rest looks same.
I converted using,
`self.model.cuda().eval()`
`dummy_input = torch.rand(1, 3,416, 416).cuda()`
`torch.onnx.export(self.model, dummy_input, "trk.onnx", export_params=True, verbose=True)`

converted using onnx-simplifier
`python3 -m onnxsim input_model output_model`

and ran it using
`model =  onnxruntime.InferenceSession("trk.onnx")`
`input_name = sess.get_inputs()[0].name`
`label_name = sess.get_outputs()[0].name`
`pred = sess.run(None, {input_name: im_blob})`

**Actual output (onnx):**
pred11 = [[[ 0.0429871 0.10708108 -0.15831867 ... -0.05099011 0.04215946 0.03529864]

[ 0.15205492 0.14381851 -0.4134867 ... -0.02547888 0.02003362 0.05678646]
[ 0.11788099 0.21649244 -0.49855745 ... -0.03875189 -0.00112192 0.05244121]
...
[-0.02988242 -0.02718411 0.17555043 ... -0.05482839 -0.03526874 -0.01705099]
[-0.02175785 -0.01682113 0.20047602 ... -0.04242673 0.00226362 0.00717632]
[-0.01177015 -0.02307639 0.05427436 ... -0.03097095 0.00717672 0.00656337]]] 218 float32

**Expected output (.pt):**
pred22 = [[[ 4.3859973e+00 3.2662495e+01 8.7064598e+01 ... -5.0997593e-02 4.2160533e-02 3.5292290e-02]
[ 4.7508678e+01 4.3868427e+01 6.7454163e+01 ... -2.5484795e-02 2.0031789e-02 5.6778252e-02]
[ 7.6021790e+01 6.6031555e+01 6.1953438e+01 ... -3.8754154e-02 -1.1225204e-03 5.2439131e-02]
...
[ 3.9146216e+02 4.0653235e+02 2.1454182e+01 ... -5.4829646e-02 -3.5270575e-02 -1.7050508e-02]
[ 3.9960834e+02 4.0709204e+02 2.1995722e+01 ... -4.2428117e-02 2.2626489e-03 7.1746223e-03]
[ 4.0778818e+02 4.0675439e+02 1.9004044e+01 ... -3.0972414e-02 7.1776402e-03 6.5612365e-03]]] 218 float32

[model](https://drive.google.com/open?id=1hx1C9dDa-lumlVgSWlpsK-gP1JTWipI3) (pytorch model)

Environment
PyTorch Version (e.g., 1.0): 1.4.0
OS (e.g., Linux): ubuntu 18.04 LTS
How you installed PyTorch (conda, pip, source): pip
Python version: 3.60.2.2
CUDA/cuDNN version:10.0/7.6
GPU models and configuration: gtx - 1080 -8GB
onnx version - 1.6.0
onnxsim.__version__ - 0.2.2

**Comment by daquexian** [comment]
Thanks for your report!

Would you mind providing the onnx model exported by pytorch? so that I can check whether the mismatch is introduced by simplifying.

**Comment by sathiez** [comment]
Hi,
PFA

[pytorch](https://drive.google.com/open?id=1hx1C9dDa-lumlVgSWlpsK-gP1JTWipI3) (pytorch model)

**Comment by daquexian** [comment]
> Hi,
> PFA
> 
> [pytorch](https://drive.google.com/open?id=1hx1C9dDa-lumlVgSWlpsK-gP1JTWipI3) (pytorch model)
> [onnx](https://drive.google.com/open?id=1aVFey_J-byPMcfzAn8AzNO-OFKFLounF) (onnx model)

Thanks! I'll check it tomorrow (1 a.m. here) ;)

**Comment by daquexian** [comment]
@sathiez I ran onnxsim on your model and found the outputs before and after simplifying are the same。

You can install the latest onnxsim (version 0.2.4) by `pip3 install -U onnx-simplifier` and run `python3 -m onnxsim trk.onnx trk_sim.onnx`, then onnxsim will generate 3 random inputs to check whether the output is changed after simplifying.

so the mismatch may be introduced by pytorch->onnx. Could you please verify it?

**Comment by sathiez** [comment]
yes mismatch is from  pytorch->onnx.
