### ISSUE TITLE
[pytorch to onnx run in tengine error] ：Tengine-master/core/lib/graph_executor.cpp:357 infer shape failed on node: 454 due to input: 453 size is zero

### ISSUE THREAD

**Issue by fyq00** [daquexian/onnx-simplifier#49]
**Describe the bug**
The bug is :
/home/ff/Tengine-master/core/lib/graph_executor.cpp:357 infer shape failed on node: 454 due to input: 453 size is zero

I trained my model with Pytorch and then transfered to onnx，using Ubuntu16.04.
When I use Tengine to run my model, bug appeared,like following:
           These 3op are not supported
                {shape, Gather, Unsqueeze}

Then I try onnx_simplifier,here is the new bug:
           /home/ff/Tengine-master/core/lib/graph_executor.cpp:357 infer shape failed on node: 454 due to input: 453 size is zero

I don't know how to solve this problem~

**Comment by daquexian** [comment]
Could you please send the onnx model to daquexian566@gmail.com? Thanks!

**Comment by fyq00** [comment]
OK!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "daquexian"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 中午1:01
收件人: "daquexian/onnx-simplifier"<onnx-simplifier@noreply.github.com&gt;; 
抄送: "nabob`男人"<229247822@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [daquexian/onnx-simplifier] [pytorch to onnx run in tengine error] ：Tengine-master/core/lib/graph_executor.cpp:357 infer shape failed on node: 454 due to input: 453 size is zero (#49)





 
Could you please send the onnx model to daquexian566@gmail.com? Thanks!

**Comment by fyq00** [comment]
OK,I have sent it to you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"daquexian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 中午1:01
收件人:&nbsp;"daquexian/onnx-simplifier"<onnx-simplifier@noreply.github.com&gt;;
抄送:&nbsp;"nabob`男人"<229247822@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [daquexian/onnx-simplifier] [pytorch to onnx run in tengine error] ：Tengine-master/core/lib/graph_executor.cpp:357 infer shape failed on node: 454 due to input: 453 size is zero (#49)





 
Could you please send the onnx model to daquexian566@gmail.com? Thanks!

**Comment by daquexian** [comment]
I'm afraid that it is a bug of Tengine. "Size is zero" means the "tensor" is actually a scalar. It is not a bug but Tengine seems to fail to process it. @BUG1989 

![image](https://user-images.githubusercontent.com/11607199/77146021-ff71be00-6ac4-11ea-8def-3b05c6d7af33.png)
