### ISSUE TITLE
RuntimeError: Method run failed due to: [ONNXRuntimeError] 

### ISSUE THREAD

**Issue by Ason93** [daquexian/onnx-simplifier#5]
python3 -m onnxsim ~/code/tensorflow-onnx/tf_model/vgg16/vgg16.onnx ~/code/tensorflow-onnx/tf_model/vgg16/vgg16_sim.onnx
Simplifying...
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553438759
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553438717
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553440831
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553440837
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553440837
2019-05-15 16:42:00.053336347 [W:onnxruntime:Default, bfc_arena.cc:201 AllocateRawInternal] tried to allocate 0 bytes
2019-05-15 16:42:00.053393721 [W:onnxruntime:Default, bfc_arena.cc:201 AllocateRawInternal] tried to allocate 0 bytes
2019-05-15 16:42:00.053407540 [W:onnxruntime:Default, bfc_arena.cc:201 AllocateRawInternal] tried to allocate 0 bytes
2019-05-15 16:42:00.053416950 [W:onnxruntime:Default, bfc_arena.cc:201 AllocateRawInternal] tried to allocate 0 bytes
2019-05-15 16:42:00.053424564 [W:onnxruntime:Default, bfc_arena.cc:201 AllocateRawInternal] tried to allocate 0 bytes
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cxjin/.local/lib/python3.6/site-packages/onnxsim/__main__.py", line 22, in <module>
    main()
  File "/home/cxjin/.local/lib/python3.6/site-packages/onnxsim/__main__.py", line 15, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n)
  File "/home/cxjin/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 182, in simplify
    model_opt = eliminate_const_nodes(model_opt, get_constant_nodes(model_opt), forward_all(model_opt))
  File "/home/cxjin/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 105, in forward_all
    res = forward(model)
  File "/home/cxjin/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 97, in forward
    res = OrderedDict(zip(outputs, sess.run(outputs, inputs)))
  File "/home/cxjin/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 72, in run
    return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /onnxruntime_src/onnxruntime/core/providers/cpu/nn/pool_base.h:163 std::vector<long int> onnxruntime::PoolBase::SetOutputSize(const onnxruntime::TensorShape&, int64_t, std::vector<long int>*, const std::vector<long int>&, int64_t) const input_shape.Size() > 0 was false.
Stacktrace:

**Comment by daquexian** [comment]
Thanks for your report!

Could you please provide the ONNX model or send it to me by email? My email address is daquexian566@gmail.com

**Comment by Ason93** [comment]
> 谢谢你的报告！
> 
> 您能否提供ONNX型号或通过电子邮件发送给我？我的电子邮件地址是[daquexian566@gmail.com](mailto:daquexian566@gmail.com)

I have E-mail my pb and onnx models to you! Please check it! Thanks

**Comment by Ason93** [comment]
When I run in anothor PC with the same order, the problem is following
(I just sudo pip3 install onnxsimplifier, sudo pip3 install onnxruntime on ubuntu16.04):
python3 -m onnxsim ./models/vgg16/vgg16.onnx ./models/vgg16/vgg16_sim.onnx
Simplifying...
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553438759
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cxjin/onnx-simplifier/onnxsim/__main__.py", line 22, in <module>
    main()
  File "/home/cxjin/onnx-simplifier/onnxsim/__main__.py", line 15, in main
    model_opt = onnxsim.simplify(args.input_model, check_n=args.check_n)
  File "/home/cxjin/onnx-simplifier/onnxsim/onnx_simplifier.py", line 180, in simplify
    model_opt = optimize(model_ori)
  File "/home/cxjin/onnx-simplifier/onnxsim/onnx_simplifier.py", line 146, in optimize
    model = onnx.utils.polish_model(model)
  File "/usr/local/lib/python3.5/dist-packages/onnx/utils.py", line 18, in polish_model
    onnx.checker.check_model(model)
  File "/usr/local/lib/python3.5/dist-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.

**Comment by daquexian** [comment]
Sorry, the mode is expired, could you send me again?

**Comment by linzhirui1992** [comment]
I meet the similar problem. Has the problem been solved?
`RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : D:\3\s\onnxruntime\core/providers/cpu/nn/pool_base.h:163 onnxruntime::PoolBase::SetOutputSize input_shape.Size() > 0 was false.`

**Comment by Linchunhui** [comment]
I have the same problem.
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : D:\3\s\onnxruntime\core/providers/cpu/nn/pool_base.h:163 onnxruntime::PoolBase::SetOutputSize input_shape.Size() > 0 was false.

**Comment by quliulangle** [comment]
same problem!
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /onnxruntime_src/onnxruntime/core/providers/cpu/nn/pool_base.h:169 std::vector<long int> onnxruntime::PoolBase::SetOutputSize(const onnxruntime::TensorShape&, int64_t, std::vector<long int>*, const std::vector<long int>&, int64_t) const input_shape.Size() > 0 was false. 
Stacktrace:

**Comment by daquexian** [comment]
@linzhirui1992 @Linchunhui @quliulangle Could you please send your model to my mailbox? My email is daquexian566@gmail.com

**Comment by snehabhapkar10** [comment]
hi @daquexian , I have the same problem too
`RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /onnxruntime_src/onnxruntime/core/providers/cpu/nn/pool_base.h:163 std::vector<long int> onnxruntime::PoolBase::SetOutputSize(const onnxruntime::TensorShape&, int64_t, std::vector<long int>*, const std::vector<long int>&, int64_t) const input_shape.Size() > 0 was false.`

**Comment by dhkim0225** [comment]
I have a same problem, but cannot send you a model since there's a security issue.

**Comment by daquexian** [comment]
Could you please upload the model to google drive or something like that
and share it with me?

Thanks
