### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by corleonechensiyu** [daquexian/onnx-simplifier#50]
**Describe the bug**
Checking 0/3...
Tensor scores changes after simplifying. The max diff is 0.37125229835510254.
Note that the checking is not always correct.
After simplifying:
[[[9.3386704e-01 2.9077111e-03 2.2453293e-03 ... 1.6835716e-03
   1.1354900e-03 1.8100661e-03]
  [9.4730669e-01 1.0944547e-03 1.0280557e-03 ... 2.2252749e-03
   3.2085853e-03 3.3723232e-03]
  [9.1126448e-01 4.0056766e-03 2.4932963e-03 ... 5.8777770e-04
   2.2106536e-03 1.0412371e-03]
  ...
  [2.5697947e-01 3.6060717e-02 2.1950582e-03 ... 9.7272865e-02
   2.8366329e-02 8.7439425e-02]
  [2.8084219e-01 2.3728541e-01 3.0571911e-02 ... 7.2766706e-02
   1.6120823e-02 6.8334460e-02]
  [1.5737572e-01 1.9133696e-03 9.7480938e-03 ... 7.4628435e-02
   6.2059723e-03 3.0124951e-02]]]
Before simplifying:
[[[0.86023927 0.00735333 0.00441171 ... 0.00390399 0.00354641 0.00487716]
  [0.89039016 0.00274161 0.00309724 ... 0.00576726 0.00513357 0.00982196]
  [0.8634894  0.00552442 0.00474672 ... 0.00136774 0.00317875 0.00178858]
  ...
  [0.5530022  0.02890183 0.00509811 ... 0.03678409 0.03503098 0.03874877]
  [0.54851794 0.07100447 0.02439926 ... 0.03236982 0.02336247 0.02174926]
  [0.508326   0.00574843 0.01278591 ... 0.0319036  0.01349589 0.02038678]]]
----------------
Check failed, please be careful to use the simplified model.

**Model**
已发邮箱

**Comment by daquexian** [comment]
Thanks for your issue! I found it is a bug of onnx optimizers. Would you mind if I share your model with onnx team so that they may try to fix the bug?

**Comment by corleonechensiyu** [comment]
可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"daquexian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 中午1:12
收件人:&nbsp;"daquexian/onnx-simplifier"<onnx-simplifier@noreply.github.com&gt;;
抄送:&nbsp;"corleone"<395934383@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [daquexian/onnx-simplifier] [BUG]  (#50)





 
Thanks for your issue! I found it is a bug of onnx optimizers. Would you mind if I share your model with onnx team so that they may try to fix the bug?

**Comment by daquexian** [comment]
I have posted an issue in ONNX repo: https://github.com/onnx/onnx/issues/2677.

**Comment by corleonechensiyu** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"daquexian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 中午1:27
收件人:&nbsp;"daquexian/onnx-simplifier"<onnx-simplifier@noreply.github.com&gt;;
抄送:&nbsp;"corleone"<395934383@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [daquexian/onnx-simplifier] [BUG]  (#50)





 
I have posted an issue in ONNX repo: onnx/onnx#2677.

**Comment by daquexian** [comment]
@corleonechensiyu As a temporary workaround, you can specify `--skip-optimization` when runnin onnxsim

**Comment by corleonechensiyu** [comment]
好的 我试试



发自我的iPhone


------------------ Original ------------------

**Comment by zhuyu-cs** [comment]
#47 may also help you.

**Comment by daquexian** [comment]
@corleonechensiyu @zhuyu-cs onnx-simplifier v0.2.6 is published. It added "--skip-fuse-bn" to avoid these failures. This issue will be closed and the problem should be tracking in https://github.com/onnx/onnx/issues/2677.

**Comment by corleonechensiyu** [comment]
> @corleonechensiyu @zhuyu-cs onnx-simplifier v0.2.6 is published. It added "--skip-fuse-bn" to avoid these failures. This issue will be closed and the problem should be tracking in [onnx/onnx#2677](https://github.com/onnx/onnx/issues/2677).

谢谢大老师！

**Comment by zhuyu-cs** [comment]
daquexian dalao！！
