### ISSUE TITLE
Better Inference time than original onnx model?

### ISSUE THREAD

**Issue by rameshjesswani** [daquexian/onnx-simplifier#51]
Hi, 

Thanks for this nice contribution. Just a question, does this method has better inference time than onnx and pytorch original model?

**Comment by daquexian** [comment]
Sorry for the late reply. The main propose of onnx-simplifier is not better inference time but more compatible with inference frameworks like TensorRT and NCNN. A better inference time may be obtained as a side result as onnx-simplifier removes some redundant nodes in the model.
