### ISSUE TITLE
[BUG] Sim failed 

### ISSUE THREAD

**Issue by adty1992** [daquexian/onnx-simplifier#53]
I wanna simplify my onnx model, but I got this error message:

> onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however '592' has been used as output names multiple times.

I have send my model to aquexian566@gmail.com.

**Comment by daquexian** [comment]
I haven't received the model. I'm afraid you sent it to the wrong address. My email address is daquexian566@gmail.com :)

**Comment by onesnow123q** [comment]
我也遇到了相同的问题，请问解决了吗~~

**Comment by daquexian** [comment]
Could you please send your model to daquexian566@gmail.com?

**Comment by onesnow123q** [comment]
感谢你的回复~~
@daquexian 模型已经发送给你啦~~
报错如下：onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however '382' has been used as graph input names multiple times.

**Comment by MichealZhang** [comment]
> 感谢你的回复~~
> @daquexian 模型已经发送给你啦~~
> 报错如下：onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however '382' has been used as graph input names multiple times.

你好，想请问一下你的问题解决了吗

**Comment by daquexian** [comment]
> > 感谢你的回复~~
> > @daquexian 模型已经发送给你啦~~
> > 报错如下：onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however '382' has been used as graph input names multiple times.
> 
> 你好，想请问一下你的问题解决了吗

我最近在旅游，暂时看不了问题 QAQ

**Comment by MichealZhang** [comment]
抱歉，不好意思打扰了哈。





------------------ Original ------------------

**Comment by daquexian** [comment]
😂😂😂😂 哇，有什么抱歉 >_< 我过几天就回去，然后会看看这个问题的 QAQ

**Comment by MichealZhang** [comment]
非常感谢哈





------------------ Original ------------------

**Comment by nihui** [comment]
这个问题我遇到了
需要 --skip-fuse-bn

**Comment by MichealZhang** [comment]
哇，感谢，是在命令行加上这个参数就行了吗





------------------ Original ------------------

**Comment by daquexian** [comment]
是的，可以试一试 QAQ 没有效果的话可以再试试换成 --skip-optimization

**Comment by MichealZhang** [comment]
成功了！非常感谢！





------------------ Original ------------------

**Comment by daquexian** [comment]
是 --skip-fuse-bn 成功了还是 --skip-optimization 成功了呢 QAQ

**Comment by MichealZhang** [comment]
skip-fuse-bn





------------------ Original ------------------

**Comment by daquexian** [comment]
https://github.com/onnx/onnx/issues/2401, https://github.com/onnx/onnx/issues/2613

ONNX fuse-bn-into-conv optimizer is broken :|

**Comment by daquexian** [comment]
fuse bn optimizer is disabled by default since v0.2.8. If the problem still exists after upgrading, please feel free to report.

**Comment by daquexian** [comment]
Travis CI is under maintenance so v0.2.8 has not been published, please wait QAQ

**Comment by nihui** [comment]
QAQ

**Comment by daquexian** [comment]
v0.2.8 上传到 pypi 了

**Comment by adty1992** [comment]
great :)

**Comment by daquexian** [comment]
@SpongeBob-222 @MichealZhang 可以试一下 convertmodel.com，web 版应该没有这个问题了

**Comment by tangyanf** [comment]
hello,我最经也遇到了这个问题，当使用fuse-bn-into-conv的时候，就会有重复命名的问题出现
