### ISSUE TITLE
[BUG] error about Resize Op in Upsample layer

### ISSUE THREAD

**Issue by muzi2045** [daquexian/onnx-simplifier#56]
**Describe the bug**
environment:
Pytorch 1.4
Python3.6
onnxruntime == 1.2.0
onnx == 1.5.0
using pytorch opset11
Try to convert the Upsample layer to onnx with different func
```
# inner_top_down = F.upsample(last_inner, size=inner_lateral.shape[-2:],mode='bilinear', align_corners=False) # add to
# inner_top_down = F.interpolate(last_inner, size=inner_lateral.shape[-2:],mode='bilinear', align_corners=False) # add to
# inner_top_down = F.upsample(last_inner, size=inner_lateral.shape[-2:])
inner_top_down = F.upsample(last_inner, size=inner_lateral.shape[-2:], mode="nearest")
```
the export part in onnx:
![image](https://user-images.githubusercontent.com/12984898/78851172-b4a3f000-7a4b-11ea-8222-9d50b16c05ee.png)

And Use onnx-simplifier to simplify this onnx will occur an error in Resize Op
looks like the onnxruntime only accept max 2 input..., but the Resize op has 4 input...
![image](https://user-images.githubusercontent.com/12984898/78851243-e4eb8e80-7a4b-11ea-82e9-32e61e72a86d.png)

But this onnx file can be successfully convert to trt...
![image](https://user-images.githubusercontent.com/12984898/78851375-38f67300-7a4c-11ea-9b65-1fdcaca90195.png)

**Model**
here is the onnx file 
https://drive.google.com/file/d/1dAHmNcX20XlqirVzjDyMj4m9QcHStCbU/view?usp=sharing.
@daquexian

**Comment by daquexian** [comment]
Thanks for your issue!

opset 11 is onnx 1.6.0. Please update onnx and try again.

**Comment by muzi2045** [comment]
thanks for reply!
it works now. d(`･∀･)b
