### ISSUE TITLE
different types (tensor(int32) and tensor(int64)

### ISSUE THREAD

**Issue by chenti2x** [daquexian/onnx-simplifier#57]
problem:onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (Tind) bound to different types (tensor(int32) and tensor(int64) in node (tower_0/ShuffleNetV2/Stage2/unit_2/concat_shuffle_split/strided_slice_1).

请问，这个是什么意思呢？

**Comment by chenti2x** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/onnxsim/__main__.py", line 42, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/onnxsim/__main__.py", line 31, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, input_shapes=input_shapes)
  File "/usr/local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 303, in simplify
    res = forward_all(model, input_shapes=input_shapes)
  File "/usr/local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 158, in forward_all
    res = forward(model, input_shapes=input_shapes)
  File "/usr/local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 143, in forward
    sess = rt.InferenceSession(model.SerializeToString(), sess_options=sess_options)
  File "/usr/local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/usr/local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (Tind) bound to different types (tensor(int32) and tensor(int64) in node (tower_0/ShuffleNetV2/Stage2/unit_2/concat_shuffle_split/strided_slice_1).

**Comment by daquexian** [comment]
Thanks for your report. Could you please send your model to daquexian566@gmail.com?

**Comment by chenti2x** [comment]
我已经发到这个邮箱了。
1.我的model是pb的，我通过python3.6 -m tf2onnx.convert --input keypoints_epoch1.pb --inputs tower_0/images:0 --outputs tower_0/SpatialSqueeze:0 --output ./keypoints_epoch1_9.onnx --verbose --custom-ops --opset 10将其转换为onnx，--opset设为>=10才能转化成功。
2.之后通过咱们的工具python3.6 -m onnxsim keypoints_epoch1_10.onnx keypoints_epoch1_10_sim.onnx进行简化，简化时出现的问题。

**Comment by chenti2x** [comment]
@daquexian

**Comment by chenti2x** [comment]
@daquexian  我看到您提供的工具简化思想主要是将与nms无关的op进行修改为const op，想了解一下网络简化只有这些操作吗？有没有其他操作，例如将bn和conv融合这种可不可以进行简化？关于简化这方面知识有没有相关书籍或网络能够推荐给我？

**Comment by daquexian** [comment]
> 有没有其他操作，例如将bn和conv融合这种可不可以进行简化？关于简化这方面知识有没有相关书籍或网络能够推荐给我？

可以，这些是通过调用 onnx 内置的 optimizer 做到的。没有相关书籍，基本流程就是扫描特定的模式（例如 conv->bn），然后修改网络

**Comment by chenti2x** [comment]
哦哦哦，太感谢啦，我好好研究一下onnx 内置的 optimizer 
非常感谢！！！

**Comment by chenti2x** [comment]
请问，简化时融合掉的gather、shape、unsqueeze、concat等这些操作是我的模型转为onnx时onnx产生的还是我自己训练的model本身就有呢？我有一个pb模型并没有这些操作，那onnx-simplifier还会有作用吗？

大神，非常感谢！！！

**Comment by daquexian** [comment]
> @daquexian 请问，简化时融合掉的gather、shape、unsqueeze、concat等这些操作是我的模型转为onnx时onnx产生的还是我自己训练的model本身就有呢？我有一个pb模型并没有这些操作，那onnx-simplifier还会有作用吗？
> 
> 大神，非常感谢！！！

转 onnx 的时候产生的；会有作用

**Comment by chenti2x** [comment]
懂啦，再次感谢(❁´ω`❁)发自我的华为手机-------- 原始邮件 --------主题：Re: [daquexian/onnx-simplifier] different types (tensor(int32) and tensor(int64) (#57)发件人：daquexian 收件人：daquexian/onnx-simplifier 抄送：chenti2x <874672279@qq.com>,Author 



@daquexian 请问，简化时融合掉的gather、shape、unsqueeze、concat等这些操作是我的模型转为onnx时onnx产生的还是我自己训练的model本身就有呢？我有一个pb模型并没有这些操作，那onnx-simplifier还会有作用吗？

大神，非常感谢！！！



转 onnx 的时候产生的；会有作用

**Comment by daquexian** [comment]
QAQ 这个是 tf2onnx 转换器的问题，所以只好先关掉了
