### ISSUE TITLE
[BUG] Floating point exception (core dumped)

### ISSUE THREAD

**Issue by almogtzabari** [daquexian/onnx-simplifier#59]
Hi,
I was trying to simplify the model [Mask R-CNN R-50-FPN](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn) when I got Floating point exception (core dumped).

The command is used is:
 `python3 -m onnxsim ./mask_rcnn_R_50_FPN_1x.onnx ./optimized.onnx --input-shape "image:3,800,800"`

Any suggestions for how to solve it?
Is there any way I can see more debugging information?

**Comment by candlewill** [comment]
I meet the same problem. Do you have any solutions now?

**Comment by almogtzabari** [comment]
> I meet the same problem. Do you have any solutions now?

I really don't remember if I was able to make work on not 😅.
Sorry.
