### ISSUE TITLE
No Op registered for ReverseV2 with domain_version of 8

### ISSUE THREAD

**Issue by Zrufy** [daquexian/onnx-simplifier#64]
When i'm trying to convert my model i obtain this error.Any solution?

**Comment by daquexian** [comment]
Could you please send your model to daquexian566@gmail.com? Thanks!

**Comment by Zrufy** [comment]
i have resolved that error but now i have this 

`onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'lstm_1/strided_slice_3:0' of node:
input: "Squeeze__59:0" input: "lstm_1/strided_slice_3:0" output: "lstm_1/while/MatMul_3:0" name: "lstm_1/while/MatMul_3" op_type: "MatMul" domain: ""
 is not output of any previous nodes.

==> Context: Bad node spec: input: "trip_count__65" input: "copy__41/lstm_1/while/LogicalAnd:0" input: "lstm_2/while/iteration_counter:0" input: "lstm_2/while/iteration_counter:0" input: "lstm_1/Tile:0" input: "lstm_1/Tile:0" output: "unused_loop_output___61" output: "unused_loop_output___62" output: "unused_loop_output___63" output: "unused_loop_output___64" output: "lstm_1/TensorArrayStack/TensorArrayGatherV3:0" name: "generic_loop_Loop__66" op_type: "Loop" attribute { name: "body" g { node { input: "lstm_1/strided_slice_12__198:0" output: "lstm_1/while/Less_1__202:0" name: "lstm_1/while/Less_1__202" op_type: "Cast" attribute { name: "to" i: 1 type: INT } } node { input: "lstm_1/while/Identity_1:0" input: "lstm_2/while/add_9/y:0" output: "sub_graph_ending_node_Identity__44:0" name: "lstm_1/while/add_9" op_type: "Add" domain: "" } node { input: "sub_graph_ending_node_Identity__44:0" output: "lstm_1/while/Less_1__201:0" name: "lstm_1/while/Less_1__201" op_type: "Cast" attribute { name: "to" i: 1 type: INT } } node { input: "lstm_1/while/Less_1__201:0" input: "lstm_1/while/Less_1__202:0" output: "lstm_1/while/Less_1:0" name: "lstm_1/while/Less_1" op_type: "Less" domain: "" } node { input: "lstm_1/while/Identity_1:0" output: "Unsqueeze__56:0" name: "Unsqueeze__56" op_type: "Unsqueeze" attribute { name: "axes" ints: 0 type: INTS } domain: "" } node { input: "lstm_1/while/Identity:0" input: "lstm_2/while/add_9/y:0" output: "sub_graph_ending_node_Identity__43:0" name: "lstm_1/while/add" op_type: "Add" domain: "" } node { input: "sub_graph_ending_node_Identity__43:0" output: "lstm_1/while/Less__203:0" name: "lstm_1/while/Less__203" op_type: "Cast" attribute { name: "to" i: 1 type: INT } } node { input: "lstm_1/while/Less__203:0" input: "const_fold_opt__339" output: "lstm_1/while/Less:0" name: "lstm_1/while/Less" op_type: "Less" domain: "" } node { input: "lstm_1/while/Less:0" input: "lstm_1/while/Less_1:0" output: "sub_graph_ending_node_Identity__42:0" name: "lstm_1/while/LogicalAnd" op_type: "And" domain: "" } node { input: "lstm_1/transpose:0" input: "Unsqueeze__56:0" output: "Gather__57:0" name: "Gather__57" op_type: "Gather" domain: "" } node { input: "Gather__57:0" output: "Squeeze__59:0" name: "Squeeze__59" op_type: "Squeeze" attribute { name: "axes" ints: 0 type: INTS } domain: "" } node { input: "Squeeze__59:0" input: "lstm_1/strided_slice_3:0" output: "lstm_1/while/MatMul_3:0" name: "lstm_1/while/MatMul_3" op_type: "MatMul" domain: "" } node { input: "lstm_1/while/MatMul_3:0" input: "lstm_1/strided_slice_11:0" output: "lstm_1/while/BiasAdd_3:0" name: "lstm_1/while/BiasAdd_3" op_type: "Add" domain: "" } node { input: "lstm_1/while/Identity_3:0" input: "lstm_1/strided_slice_7:0" input: "lstm_1/while/BiasAdd_3:0" output: "Gemm__9:0" name: "Gemm__9" op_type: "Gemm" domain: "" } node { input: "lstm_2/while/mul_4/x:0" input: "Gemm__9:0" output: "lstm_1/while/mul_4:0" name: "lstm_1/while/mul_4" op_type: "Mul" domain: "" } node { input: "lstm_1/while/mul_4:0" input: "lstm_2/while/add_4/y:0" output: "lstm_1/while/add_8:0" name: "lstm_1/while/add_8" op_type: "Add" domain: "" } node { input: "lstm_1/while/add_8:0" input: "lstm_1/while/Const_3:0" output: "Min__205:0" name: "Min__205" op_type: "Min" domain: "" } node { input: "Min__205:0" input: "lstm_1/while/Const:0" output: "Max__208:0" name: "Max__208" op_type: "Max" domain: "" } node { input: "Squeeze__59:0" input: "lstm_1/strided_slice_2:0" output: "lstm_1/while/MatMul_2:0" name: "lstm_1/while/MatMul_2" op_type: "MatMul" domain: "" } node { input: "lstm_1/while/MatMul_2:0" input: "lstm_1/strided_slice_10:0" output: "lstm_1/while/BiasAdd_2:0" name: "lstm_1/while/BiasAdd_2" op_type: "Add" domain: "" } node { input: "lstm_1/while/Identity_3:0" input: "lstm_1/strided_slice_6:0" input: "lstm_1/while/BiasAdd_2:0" output: "Gemm__8:0" name: "Gemm__8" op_type: "Gemm" domain: "" } node { input: "Gemm__8:0" output: "lstm_1/while/Tanh:0" name: "lstm_1/while/Tanh" op_type: "Tanh" domain: "" } node { input: "Squeeze__59:0" input: "lstm_1/strided_slice_1:0" output: "lstm_1/while/MatMul_1:0" name: "lstm_1/while/MatMul_1" op_type: "MatMul" domain: "" } node { input: "lstm_1/while/MatMul_1:0" input: "lstm_1/strided_slice_9:0" output: "lstm_1/while/BiasAdd_1:0" name: "lstm_1/while/BiasAdd_1" op_type: "Add" domain: "" } node { input: "lstm_1/while/Identity_3:0" input: "lstm_1/strided_slice_5:0" input: "lstm_1/while/BiasAdd_1:0" output: "Gemm__7:0" name: "Gemm__7" op_type: "Gemm" domain: "" } node { input: "lstm_2/while/mul_4/x:0" input: "Gemm__7:0" output: "lstm_1/while/mul_1:0" name: "lstm_1/while/mul_1" op_type: "Mul" domain: "" } node { input: "lstm_1/while/mul_1:0" input: "lstm_2/while/add_4/y:0" output: "lstm_1/while/add_4:0" name: "lstm_1/while/add_4" op_type: "Add" domain: "" } node { input: "lstm_1/while/add_4:0" input: "lstm_1/while/Const_3:0" output: "Min__211:0" name: "Min__211" op_type: "Min" domain: "" } node { input: "Min__211:0" input: "lstm_1/while/Const:0" output: "Max__214:0" name: "Max__214" op_type: "Max" domain: "" } node { input: "Max__214:0" input: "lstm_1/while/Identity_4:0" output: "lstm_1/while/mul_2:0" name: "lstm_1/while/mul_2" op_type: "Mul" domain: "" } node { input: "Squeeze__59:0" input: "lstm_1/strided_slice:0" output: "lstm_1/while/MatMul:0" name: "lstm_1/while/MatMul" op_type: "MatMul" domain: "" } node { input: "lstm_1/while/MatMul:0" input: "lstm_1/strided_slice_8:0" output: "lstm_1/while/BiasAdd:0" name: "lstm_1/while/BiasAdd" op_type: "Add" domain: "" } node { input: "lstm_1/while/Identity_3:0" input: "lstm_1/strided_slice_4:0" input: "lstm_1/while/BiasAdd:0" output: "Gemm__6:0" name: "Gemm__6" op_type: "Gemm" domain: "" } node { input: "lstm_2/while/mul_4/x:0" input: "Gemm__6:0" output: "lstm_1/while/mul:0" name: "lstm_1/while/mul" op_type: "Mul" domain: "" } node { input: "lstm_1/while/mul:0" input: "lstm_2/while/add_4/y:0" output: "lstm_1/while/add_2:0" name: "lstm_1/while/add_2" op_type: "Add" domain: "" } node { input: "lstm_1/while/add_2:0" input: "lstm_1/while/Const_3:0" output: "Min__217:0" name: "Min__217" op_type: "Min" domain: "" } node { input: "Min__217:0" input: "lstm_1/while/Const:0" output: "Max__220:0" name: "Max__220" op_type: "Max" domain: "" } node { input: "Max__220:0" input: "lstm_1/while/Tanh:0" output: "lstm_1/while/mul_3:0" name: "lstm_1/while/mul_3" op_type: "Mul" domain: "" } node { input: "lstm_1/while/mul_2:0" input: "lstm_1/while/mul_3:0" output: "sub_graph_ending_node_Identity__46:0" name: "lstm_1/while/add_6" op_type: "Add" domain: "" } node { input: "sub_graph_ending_node_Identity__46:0" output: "lstm_1/while/Tanh_1:0" name: "lstm_1/while/Tanh_1" op_type: "Tanh" domain: "" } node { input: "Max__208:0" input: "lstm_1/while/Tanh_1:0" output: "sub_graph_ending_node_Identity__45:0" name: "lstm_1/while/mul_5" op_type: "Mul" domain: "" } name: "tf2onnx" initializer { data_type: 1 name: "const_fold_opt__339" raw_data: "\000\000\000B" } input { name: "i__48" type { tensor_type { elem_type: 7 shape { } } } } input { name: "cond__50" type { tensor_type { elem_type: 9 shape { } } } } input { name: "lstm_1/while/Identity:0" type { tensor_type { elem_type: 6 shape { } } } } input { name: "lstm_1/while/Identity_1:0" type { tensor_type { elem_type: 6 shape { } } } } input { name: "lstm_1/while/Identity_3:0" type { tensor_type { elem_type: 1 shape { dim { dim_param: "unk__560" } dim { dim_param: "unk__561" } } } } } input { name: "lstm_1/while/Identity_4:0" type { tensor_type { elem_type: 1 shape { dim { dim_param: "unk__562" } dim { dim_param: "unk__563" } } } } } output { name: "sub_graph_ending_node_Identity__42:0" type { tensor_type { elem_type: 9 shape { } } } } output { name: "sub_graph_ending_node_Identity__43:0" type { tensor_type { elem_type: 6 shape { } } } } output { name: "sub_graph_ending_node_Identity__44:0" type { tensor_type { elem_type: 6 shape { } } } } output { name: "sub_graph_ending_node_Identity__45:0" type { tensor_type { elem_type: 1 shape { dim { dim_param: "unk__564" } dim { dim_param: "unk__565" } } } } } output { name: "sub_graph_ending_node_Identity__46:0" type { tensor_type { elem_type: 1 shape { dim { dim_param: "unk__566" } dim { dim_param: "unk__567" } } } } } output { name: "sub_graph_ending_node_Identity__45:0" type { tensor_type { elem_type: 1 shape { dim { dim_param: "unk__564" } dim { dim_param: "unk__565" } } } } } } type: GRAPH } domain: ""`

**Comment by daquexian** [comment]
Could you please try passing `--skip-optimization` to onnxsim?

**Comment by Zrufy** [comment]
the conversion now is fine!The problem now is for ncnn for this layer ReduceSum not supported yet!
  # axes 7
  # keepdims=0
Unsqueeze not supported yet!
  # axes 7
Tile not supported yet!
Loop not supported yet!
  # body 5
ReduceSum not supported yet!
  # axes 7
  # keepdims=0
Unsqueeze not supported yet!
  # axes 7
Tile not supported yet!
Loop not supported yet!
  # body 5
ReduceMax not supported yet!
  # axes 7
  # keepdims=1
ReduceSum not supported yet!
  # axes 7
  # keepdims=1

if you have some information about that.If no i close the issue.Thanks for the help.

**Comment by daquexian** [comment]
> the conversion now is fine!The problem now is for ncnn for this layer ReduceSum not supported yet!
>   # axes 7
>   # keepdims=0
> Unsqueeze not supported yet!
>   # axes 7
> Tile not supported yet!
> Loop not supported yet!
>   # body 5
> ReduceSum not supported yet!
>   # axes 7
>   # keepdims=0
> Unsqueeze not supported yet!
>   # axes 7
> Tile not supported yet!
> Loop not supported yet!
>   # body 5
> ReduceMax not supported yet!
>   # axes 7
>   # keepdims=1
> ReduceSum not supported yet!
>   # axes 7
>   # keepdims=1
> 
> if you have some information about that.If no i close the issue.Thanks for the help.

Happy to hear that. The new problem looks like that ncnn itself doesn't support those onnx operators. AFAIK there is no good solution for it.
