### ISSUE TITLE
[Run successfully but there is still some Gather operators have not been simplified ] 

### ISSUE THREAD

**Issue by vuthede** [daquexian/onnx-simplifier#69]
**Describe the bug**
After install the tool and run simplifying the model, It was successful, but after that I used the  [Netron app](https://github.com/lutzroeder/netron) to visualize the model. I still see some Gather operations (near the end of the visualizing graph) have not been simplified.
![Screenshot from 2020-05-20 18-06-36](https://user-images.githubusercontent.com/19920599/82427967-c05fe900-9ac4-11ea-89d8-3004193e5ec3.png)

**Model**
Here is the [link](https://drive.google.com/file/d/1GJOv0Sszi0KkgMd5ipKuccKH_pOjK6Kk/view?usp=sharing) to download my model

I am looking forward to get all of your resonse. Thanks

**Comment by daquexian** [comment]
Thanks for your report!

onnxsim cannot eliminate all gather op. It is by design. Only the ops with constant inputs can be eliminated.

**Comment by vuthede** [comment]
Ok thank you!

**Comment by budaLi** [comment]
> Ok thank you!

Hi,can you tell me  the method you slove it ? i failled when i try trans it to caffe model
