### ISSUE TITLE
Conversion from TF2->onnx->ncnn

### ISSUE THREAD

**Issue by Zrufy** [daquexian/onnx-simplifier#70]
I try to convert my mobilenet pretrained to onnx to ncnn but when i go to inference my model i have a core dumped by ncnn.Have you some solution for this problem?

**Comment by daquexian** [comment]
thanks for your report. could you please send your model to my email,
daquexian566@gmail.com? thanks!

Vincenzo Fornaro <notifications@github.com> 于 2020年5月22日周五 下午6:49写道：

**Comment by Zrufy** [comment]
i'm sorry for the late.The model is a mobilnetV2 trained with tensorflow 2,0.

**Comment by Zrufy** [comment]
@daquexian can you help me?

**Comment by daquexian** [comment]
I'll be appreciated if you could provide the onnx model :) I'm not familiar with tf
