### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by poincarelee** [daquexian/onnx-simplifier#71]
when  use onnx in a script, I  met the error: "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)", is there any solution on this ?

**Comment by poincarelee** [comment]
have solved this problem,  import onnx before import torch would be the solution.

**Comment by zylo117** [comment]
It doesn't work for me, but when I set `do_constant_folding=False` at `torch.onnx.export`, it works
