### ISSUE TITLE
[BUG] core dumped when run onnxsim

### ISSUE THREAD

**Issue by buqing2009** [daquexian/onnx-simplifier#77]
**Describe the bug**
when i run onnx-sim, it return:
`[1]    10193 segmentation fault (core dumped)  python -m onnxsim  
`

**Model**
[model](https://drive.google.com/file/d/1-UdxJU6w_lkibeQzlI5N64135cmVmbMf/view?usp=sharing)

**Comment by buqing2009** [comment]
有可能是这个原因
[comment](https://github.com/daquexian/onnx-simplifier/issues/33#issuecomment-606996575)

**Comment by skurzhanskyi** [comment]
Getting the same error

**Comment by daquexian** [comment]
@buqing2009 Sorry for the late reply. I just fixed it in v0.2.12. Please upgrade your onnxsim and run it with `--skip-shape-inference` command-line argument. Thanks!
