### ISSUE TITLE
[BUG] output from model after use 'ONNX Simplifier' not same with output from original model

### ISSUE THREAD

**Issue by quangphap208** [daquexian/onnx-simplifier#79]
**Describe the bug**
I have pytorch model download from https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing. I converted from pytortch to onnx. Then, i used 'ONNX Simplifier'. However,  output from model after use 'ONNX Simplifier' not same with output from original model.

**Model**
original model: face_parsing.onnx.zip

**Comment by daquexian** [comment]
Sorry for the late reply. It is a known bug of the ONNX optimizer. I have updated onnxsim to bypass this problem. Please upgrade onnx-simplifier to 0.2.11.

**Comment by Hiperdyne19012** [comment]
> Sorry for the late reply. It is a known bug of the ONNX optimizer. I have updated onnxsim to bypass this problem. Please upgrade it to 0.2.11. Thanks!

It is happening even with skipping optimization. The output shape is being changed.

**Comment by daquexian** [comment]
> It is happening even with skipping optimization. The output shape is being changed.

@Hiperdyne19012 Could you please send the model to daquexian566@gmail.com? Thanks!

**Comment by Hiperdyne19012** [comment]
Sent

​

シャハリアル

________________________________

**Comment by daquexian** [comment]
@Hiperdyne19012 Thanks. I checked it on my machine but the output shapes remain the same. I have replied to you by email. Could you check it again? Thanks!

**Comment by Hiperdyne19012** [comment]
@daquexian Thank you! It seems Nvidia onnx to TensorRT engine converted is changing the output dimension. I thought it was the ONNX Simplifier instead, I am rechecking.

**Comment by Hiperdyne19012** [comment]
@daquexian Thank you very much! It seems the problem is the Pytorch ONNX exporter, the dimension was supposed to be [1,48,160,160] for 3629.
​

**Comment by Hiperdyne19012** [comment]
@daquexian  OK, I finally solved it, it was supported to be 34(pairs of human joints from COCO) all along not 48. [1,34,160,160] for 3629 is the correct output. I checked it with https://lutzroeder.github.io/netron, In the last stage [34, 48,1,1] gets dilated to [1,34,160,160]. Sorry for the trouble.
