### ISSUE TITLE
Your model ir_version is higher than the checker's.

### ISSUE THREAD

**Issue by zengwbz** [daquexian/onnx-simplifier#80]
torch==1.5.0
onnx==1.3.0
onnx-simplifier==0.2.9
When python -m onnxsim yolact.onnx yolact-sim.onnx, Get Error onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.

**Comment by daquexian** [comment]
please try upgrading dependencies by `pip3 install -U --upgrade-strategy eager onnx-simplifier`

**Comment by daquexian** [comment]
Closing. Please feel free to reopen it if the problem still exists.

**Comment by dzyjjpy** [comment]
@zengwbz have you solved the issue? I  met same one when converting onnx2coreml(hrnet trained by mmseg)
