### ISSUE TITLE
When support the Dynamic Shapes input？

### ISSUE THREAD

**Issue by oyrq** [daquexian/onnx-simplifier#86]
Thanks.

**Comment by daquexian** [comment]
Thanks for your issue! Dynamic input shapes will be supported soon

**Comment by oyrq** [comment]
> Thanks for your issue! Dynamic input shapes will be supported soon

@daquexian Great!

**Comment by oyrq** [comment]
@daquexian 
Hi, the Dynamic input shapes doesn't work.
onnxsim/onnx_simplifier.py", line 108, in generate_rand_input  'please determine the input size manually by --input-shape xxx'.format(key))

**Comment by oyrq** [comment]
@daquexian 
I want to use a Dynamic batch, 1.onnx input shape is [batch,3,640,640].
Hi, I don't know if the Dynamic input shapes  works properly, I use a command "python -m onnxsim 1.onnx 1_sim.onnx --input-shape 5,3,640,640", when the TensorRT load the 1_sim.onnx to make a output-shape mistake, output_shape should be [5,1280,4], but get output_shape:[5,-1,4], I have only a Dynamic batch.

**Comment by daquexian** [comment]
dynamic input shape is supported in v0.2.24 :D

**Comment by daquexian** [comment]
BTW, 

> Hi, I don't know if the Dynamic input shapes works properly, I use a command "python -m onnxsim 1.onnx 1_sim.onnx --input-shape 5,3,640,640", when the TensorRT load the 1_sim.onnx to make a output-shape mistake, output_shape should be [5,1280,4], but get output_shape:[5,-1,4], I have only a Dynamic batch.

I think it is not related to the dynamic shape of the input. It is so strange.
