### ISSUE TITLE
Unknown error : developers

### ISSUE THREAD

**Issue by manojbhatD** [daquexian/onnx-simplifier#88]
![image](https://user-images.githubusercontent.com/67604767/91287949-63786c80-e75e-11ea-9dea-5a8b65899ab2.png)

I face this error.
What might be the issue?

Model: https://drive.google.com/file/d/1BTPaFAM4iu4kXR_QImqKv0s9djC81St2/view?usp=sharing

**Comment by daquexian** [comment]
Thanks for your report. onnx-simplifier web version is in beta. You can try the python version: `pip3 install onnx-simplifier` and `python3 -m onnxsim input_onnx_model output_onnx_model`
