### ISSUE TITLE
[BUG] the problem of Concat ops merge

### ISSUE THREAD

**Issue by muzi2045** [daquexian/onnx-simplifier#94]
**Describe the bug**
here is the original model onnx :
![image](https://user-images.githubusercontent.com/12984898/95533024-ab083e80-0a14-11eb-9e32-ad60d3598a27.png)

and here is the converted model onnx graph:
![image](https://user-images.githubusercontent.com/12984898/95533069-c96e3a00-0a14-11eb-8a8e-0b092638f18b.png)

the version of onnx-simplfier==0.2.16, it looks like optimization process merged the concat ops together, but it's not we want.
**Model**

[pfe_16000.onnx.tar.gz](https://github.com/daquexian/onnx-simplifier/files/5352107/pfe_16000.onnx.tar.gz)

@daquexian

**Comment by daquexian** [comment]
Thanks for your report! Please run onnxsim with `--skip-optimizer fuse_consecutive_concats`
